### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#1]
Wir sollten die Oberfläche frühzeitig auf I18N umstellen (damit man das konsequent für alle Oberflächenelemente mitdenkt) und die Oberfläche nach deutsch übersetzen.

**Comment by rowe42** [comment]
Außerdem sollten wir uns einigen, ob die Sprache für Elemente, Attribute usw. deutsch oder englisch sein soll.

**Comment by xdoo** [comment]
Punkt zwei gehört aus meiner Sicht nicht zu i18n - sollte also dann ein eigenes Issue sein. Ich antworte jetzt trotzdem mal darauf. Empfehlung ist, die Dinge in der DSL auf English zu beschreiben. Der deutsche Plural hat einfach ein paar Tücken, die er im Englischen nicht hat. Dort ist es in der Regel damit getan ein 's' dran zu hängen. Da sich Element- und Attributnamen aus dem Modell ergeben, wäre es sinnvoll dort einen Mix aus English und Deutsch zu vermeiden. D.h. wir sollten alles in Englisch machen.

**Comment by maxerl** [comment]
Wenn wir im Modell z.B. eine deutsche Entität "Tier" verwenden, dann werden so amüsante Links wie "http://localhost:35199/tiers" für die Liste aller Tiere generiert. Im Englischen ist das sehr viel einfacher durch Anhängen von "s" ("Animal" -> "Animals").
Wir sollten deshalb die Generierung/Modellierung auf Englisch machen, aber in der UI gleich mit I18N-Mechanismen arbeiten und alle Texte auf Deutsch anzeigen.

**Comment by xdoo** [comment]
So ist das aktuell auch gelöst. Natürlich bekommst du keine adhoc Übersetzung hin. D.h. wenn ich auf das Knöpfchen drücke, dann werden dort auf der Oberfläche erst einmal die englischen Entität- und Attributnamen stehen.

**Comment by xdoo** [comment]
Ich habe für 'enclosures' exemplarisch eine zentrale i18n Lösung implementiert. Diese muss jetzt auf die anderen Entitäten übernommen werden. Dafür mache ich aber extra Tickets auf. Ich werde die Lösung jetzt dokumentieren und dann dieses Ticket schließen.

**Comment by dragonfly28** [comment]
Was ist in der Wiki-Doku mit "zentrale Übersetzung nicht möglich" gemeint? Welches Problem wird durch die eigene i18n-behavior gelöst?
Warum nehmen wir nicht einfach "PolymerElements/app-localize-behavior" out of the box?
-> siehe https://www.polymer-project.org/2.0/toolbox/localize

**Comment by xdoo** [comment]
Aus meiner Sicht laden all diese Lösungen (inkl. "PolymerElements/app-localize-behavior") die Übersetzungen in der Komponente und nicht von zentrale Stelle. D.h. jedesmal wenn eine Komponente gerendert wird, werden die Übersetzungen geladen. Man hat also bei einem Seitenaufbau mit X Komponenten X LAdevorgänge vom Server. Genau dieses Problem löst (wie in der Doku beschrieben) die eigene i18n Behavior.

Btw. ich konnte "app-localize-behavior" auf webcomponents.org nicht finden. Vielleicht war ich ja auch nur zu blöd zum Suchen.

**Comment by xdoo** [comment]
Doku wird erst fertig gestellt, wenn geklärt ist, wie dokumentiert werden soll. Bis dahin wird das issue offen bleiben. Der aktuelle Stand der Dokumentation ist unter https://github.com/xdoo/lhm_animad_admin_html5/wiki/i18n-in-der-Anwendung zu finden

**Comment by xdoo** [comment]
Ich habe die Doku unter https://github.com/xdoo/lhm_animad_admin_html5/wiki/i18n-in-der-Anwendung fertig gemacht. Ggf muss ein neues Issue für den Umzug erstellt werden. Damit ist das Ticket abgeschlossen.

**Comment by rowe42** [comment]
Habe die Doku angeschaut. Ich glaube es gibt einen Fehler im Beispiel unter "Verwendung in JavaScript". 
"relation_list" ist definiert als "Wärter für das Gehege ist %{firstname} %{lastname} mit der ID %{id}.", ich würde also die Parameter firstname, lastname und id benötigen.
Befüllt wird dann aber: this.t('relation_list', {id: item.id, name: item.name, cleaningTime: item.cleaningTime});
Das müsste doch heißen: this.t('relation_list', {firstname: item.firstname, lastname: item.name, id: item.id});

**Comment by xdoo** [comment]
Hab's geändert.
