### ISSUE TITLE
Filtern in Tabellen

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#102]
Neues Ticket für Filtern um die Diskussion mit Suche aus #60 zu trennen.

**Comment by ejcsid** [comment]
@xdoo @dragonfly28 @rowe42 @Baumfrosch

**Comment by ejcsid** [comment]
Bisherige diskutiert:
1. Es werden alle Datensätze komplett beim Öffnen der Seite geladen
2. Wir machen keine Filterfelder über den Spalten
3. Paginierung brauchen wir nicht.
4. Es braucht keine vorgefertigte Filter.

Bisher ist es so implementiert, dass 
1. bei Eingabe in das Filter-Feld, sofort nach dem eingegebenen Inhalt neu gefiltert wird. (ohne Enter)
2. in allen angezeigten Feldern (außer der ID) gefiltert wird (also bei Eingabe von "ha" wird geprüft, ob Vorname, Nachname, Erfahrung, Gehalt, Geburtstag oder Einstellungsdatum "ha" enthalten)

**Comment by Baumfrosch** [comment]
Wenn ich es richtig verstanden habe, sind Strings mit blank dazwischen mit ODER verknüpft. D.h. die Trefferliste wird größer mit jedem String. 
Wäre ein UND nicht besser? Dann würde jeder String die Liste weiter einschränken.

**Comment by ejcsid** [comment]
Im Moment interpretiert das System die Eingabe als einen String - auch wenn ein Blank eingegeben wurde. Es gibt also kein UND oder ODER. Wenn die Eingabe 'Wer Mat' ist, woher weiß das System, dass es nach Nachname='wer*' und Vorname='mat*' gefiltert werden soll?
