### ISSUE TITLE
Liste: Edit-Button zu jeder Spalte

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#104]
Soll in das Formular zum Lesen/Editieren wechseln

**Comment by Baumfrosch** [comment]
Bitte Icon vorsehen. Kann ich davon ausgehen, dass die Icons in einer Konfigurationsdatei liegen und später geändert werden können?

**Comment by xdoo** [comment]
Hier müssen wir die View wechseln und gleichzeitig den Link aus dem HAL Objekt setzen. Wollen wir uns dazu morgen mal beraten, wie wir das machen?

**Comment by ejcsid** [comment]
Edit Button ist ein Icon. Der Wechsel zur Update-Form (und bei Klick auf Neu-Button zur Create-Form) geht.

Aber noch 2 Probleme (im Branch)
1. Klicke ich dann wieder auf 'Keepers' im Menü, dann tut sich nichts.
2. Bei der Update-Form wird der ausgewählte Datensatz erst beim Klick auf den Reload-Button angezeigt.

@xdoo @rowe42 Kann mir jemand (insbesondere für den 1. Punkt) helfen?

**Comment by xdoo** [comment]
Kannst du noch kurz eine Stelle im Code referenzieren. Nur zur Orientierung. Ich finde es nämlich gerade nicht :)

**Comment by ejcsid** [comment]
Offene Punkte zur Navigation in eigene issues aufgenommen: #147 und #148
