### ISSUE TITLE
Suche über Relationen

### ISSUE THREAD

**Issue by Baumfrosch** [xdoo/lhm_animad_admin_html5#106]
Es gibt zwei Entitäten, die eine 1:n Beziehung haben, z.B. Fall und Aktivität. Kann ich Attribute der verknüpften Entität in die Suche einbeziehen? Im Beispiel: alle Fälle, die eine Aktivität haben mit Fälligkeit = heute

**Comment by Dr-Thomas-Tensi** [comment]
Die Frage ist halt, wie weit diese Logik gehen soll. Im extremen Fall kannst Du dann über das gesamte Objektnetz navigieren, also z.B. einen Fall suchen mit einer Aktivität, dessen Ort in Niederbayern liegt.
Dann wird der Query-Dialog schnell kompliziert.
Was man sich aber vorstellen könnte ist, dass man _abgeleitete Attribute_ im Klassenmodell zulässt, d.h. Attribute deren Wert sich durch Berechnung aus anderen ergibt (das gibt es auch standardmäßig in der UML). Die Berechnung darf auch Satellitenobjekte einbeziehen.
Deine eingeforderte Flexibiltät erreicht man natürlich damit nicht, aber man kann bestimmte Standardsituationen damit abfrühstücken.

**Comment by xdoo** [comment]
Du kannst über alle indizierten Felder suchen. Aber du musst das Ergebnis auch noch die Struktur bekommen. Ich würde sagen generisch nein. Wenn das wirklich eine Anforderung ist, dann muss der Entwickler das implementieren.

**Comment by Baumfrosch** [comment]
Das passt für mich. Ich möchte ohnehin einen Prozess etablieren, der dafür sorgt, dass händische Ergänzungen geprüft werden, ob sie in den Generator kommen sollen, oder als Best-Practice in die Referenzimplementierung.
