### ISSUE TITLE
Objektsuche: zuviele Datensätze (Backend)

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#107]
Anforderung aus Ticket: #60: Wenn die Suche zu viele Datensätze liefert, soll ein Hinweis kommen, dass die Suche verfeinert werden muss. Dies muss vom Backend unterstützt werden.

**Comment by ejcsid** [comment]
@rowe42 @xdoo @dragonfly28 @Baumfrosch
Neues Ticket für das Backend und Meilenstein 1. Außer, diese Anzeige kann auch auf Meilenstein 2 geschoben werden. Ich mache noch ein extra Ticket für das Frontend auf, weil sonst kann ich #60 nicht schliessen.

**Comment by Baumfrosch** [comment]
@rowe kannst du die Mengengerüste von BeZweck besorgen? Damit wir entscheiden können, in welchen Meilenstein wir das tun.

**Comment by rowe42** [comment]
Eingecheckt und Pull Request #11 für @ejcsid erstellt.
