### ISSUE TITLE
Objektsuche: zuviele Datensätze (Frontend)

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#108]
Anforderung aus #60. Kann erst umgesetzt werden, wenn #107 implementiert ist. 

@xdoo @rowe42 @dragonfly28 @Baumfrosch

**Comment by rowe42** [comment]
@ejcsid Ist eigentlich dir zugeordnet, aber ich habe das jetzt gleich mitgemacht, als ich das Backend umgesetzt habe. Hoffe das war ok.

**Comment by ejcsid** [comment]
Getestet und gemerged.
