### ISSUE TITLE
Dynamisches Nachladen von Werten bei der Auswahl von Relationen

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#120]
Will man eine Relation auswählen, so wird aktuell die gesamte Liste an Relationsobjekten (z.B. Wärter) in den Speicher geladen. Dies funktioniert bei kleineren Datenmengen sicher gut, wird die Liste sehr groß, so ist es oft sinnvoller die Daten dynamisch zu laden. 

Dieses Issue betrifft definitiv das Frontend, ggf. auch das Backend.

**Comment by ejcsid** [comment]
Duplikat
