### ISSUE TITLE
'on the fly' Relation für Enclosure und Animal

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#122]
In den Komponenten `animad-enclosure-simple-relation` und `animad-animal-simple-relation` muss die Möglichkeit eingebaut werden, Relationsobjekte 'on the fly' zu erstellen. Dies wurde exemplarisch an der Komponente `animad-keeper-simple-relation` durchgeführt. Achtung: Innerhalb der `animad-*-form` Komponenten müssen auch jeweils Anpassungen vorgenommen werden.

siehe hierzu auch #56

**Comment by dragonfly28** [comment]
siehe auch #96

**Comment by dragonfly28** [comment]
Wo kann man die 'on the fly'-Relation sehen? Da müsste doch bei den Animals etwas zu sehen sein weil dort die animad-keeper-simple-relation verwendet wird? Welche Anpassungen müssen in den Forms gemacht werden? Gibt's da ein Beispiel?

**Comment by xdoo** [comment]
Bei den `Animals` passt m.M. nach die Payload nicht. Der Button wird abhängig vom vorhandenen Link zu Keepers angezeigt. Bei `Enclosure` funktioniert es:

![screenshot-2018-1-26 animad](https://user-images.githubusercontent.com/712911/35427156-08a6028c-0268-11e8-9f8f-04b8a50c81e3.png)

Das ist das kleine + im Suchfeld.

**Comment by xdoo** [comment]
Hier noch die Payload zu dem Beispiel oben:
```json
{
  "name": "Elephant's Paradise",
  "cleaningTime": "15:15:00",
  "_links": {
    "self": {
      "href": "http://demo6512140.mockable.io/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5"
    },
    "enclosure_": {
      "href": "http://demo6512140.mockable.io/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5"
    },
    "animalList": {
      "href": "http://demo6512140.mockable.io/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5/animalList"
    },
    "animals": {
        "href": "http://demo6512140.mockable.io/animals"
    },
    "keeperList": {
      "href": "http://demo6512140.mockable.io/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5/keeperList"
    },
    "keepers": {
        "href": "http://demo6512140.mockable.io/keepers"
    }
  }
}
```
Entscheidend ist der Link mit dem Alias 'keepers'. Wenn der nicht drin ist, dann hat er keine Adresse um ein neues Objekt anzulegen. Dann hat er übrigens auch keine Listeneinträge zum Suchen.

**Comment by dragonfly28** [comment]
Geschlossen durch PR #142
