### ISSUE TITLE
KeyCloak: Einbinden in OpenShift

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#125]
Was ist zu beachten, wenn KeyCloak (was wohl außerhalb von OpenShift aufgebaut wird) durch eine Anwendung in OpenShift genutzt wird? Macht das irgendeinen Unterschied?
Kann die OpenShift-Anwendung den KeyCloak direkt aufrufen (was sie beim Authorization Code Flow muss) oder sind dafür irgendwelche Freischaltungen o.ä. nötig?

Siehe hierzu auch Issue #90 und #85.

**Comment by Baumfrosch** [comment]
Sollten wir nicht Nick hier einbinden, @rowe42?

**Comment by rowe42** [comment]
Klar.

**Comment by rowe42** [comment]
Siehe Doku internes Wiki (CAP)
