### ISSUE TITLE
Routing in Formularen

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#128]
In den Formularen müssen auf die Buttons Routings gelegt werden.

**Comment by dragonfly28** [comment]
@ejcsid: Silke, Du hast hier schon ganz viel gemacht - gibt es da eine allgemeine Lösung?
Macht dieses Issue separat von Deiner Arbeit Sinn oder soll ich es Dir zuweisen oder ganz schliessen? Oder auf andere Issues verweisen?

**Comment by ejcsid** [comment]
In den Formularen habe ich nichts gemacht, d.h. wenn dort auf 'Speichern' oder 'Abbrechen' geklickt wird, dann passiert keine Navigation auf eine andere Seite. Das muss noch eingebaut werden.

**Comment by dragonfly28** [comment]
Ich habe ein funktionierendes, einfaches Beispiel lokal ausprobiert und fange morgen mal mit dem "Cancel"-Button bei den Animals an. Betroffen sind voraussichtlich:
- animad_animals_view
- animad_animals_create_form
- animad_animals_update_form
- animad_form_behavior

**Comment by rowe42** [comment]
Erledigt.
