### ISSUE TITLE
'Abbrechen' Button für Formulare

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#131]
Aktuell kann man in den Formularen nur speichern und zurücksetzen (dann wird der Formularinhalt gelöscht). D.h. man kommt ohne zu speichern nicht mehr auf 'legalem' Wege aus dem Formular heraus. Deswegen ist ein (optionaler) Button 'Abbrechen' notwendig.

**Comment by Dr-Thomas-Tensi** [comment]
Wir müssen sowieso noch über die Transaktionslogik der Formulare reden. Mein Ansatz wäre - wie im Paper beschrieben - "Formular = Transaktion", d.h. beim Verlassen muss man entweder speichern, verwerfen oder bleiben. Änderungen in Objekten in Relationstabellen sind geschachtelte Transaktionen, d.h. man darf ändern, ohne dass das außenstehende Objekt gespeichert werden muss.
Es ist aber möglich, dass das vom Arbeitsablauf zu restriktiv ist.
