### ISSUE TITLE
Webcomponents bei "polymer build"

### ISSUE THREAD

**Issue by grimkroton** [xdoo/lhm_animad_admin_html5#134]
Nach einem Openshift s2i fehlen die webcomponents

`Laden fehlgeschlagen für das <script> mit der Quelle "http://bower-test.apps.10.0.0.40.nip.io/bower_components/webcomponentsjs/webcomponents-lite.js".
bower-test.apps.10.0.0.40.nip.io:82
Laden fehlgeschlagen für das <script> mit der Quelle "http://bower-test.apps.10.0.0.40.nip.io/bower_components/fetch/fetch.js".
bower-test.apps.10.0.0.40.nip.io:83`

**Comment by rowe42** [comment]
Bin nicht sicher, was ein s2i ist, aber beim lokalen `polymer build` steht in der Datei polymer.json im Bereich extraDependencies, dass die Datei webcomponents-lite.js in den Build zu integrieren ist. Vielleicht hilft das ja.

**Comment by rowe42** [comment]
Oberfläche wird als JAR ins API-Gateway reingeholt, deswegen kein JS-Build im Container selbst. Issue wird geschlossen.
