### ISSUE TITLE
OpenShift: Frontend bauen, in API-Gateway einbinden und deployen

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#136]
Siehe Titel

**Comment by xdoo** [comment]
Der Titel sagt viel, aber ich glaube das sind eigentlich drei Issues :) 

1. Issue: Wie bauen wir die Applikation? Da wir ja nicht immer lokal bauen wollen, muss man sich m. M. nach auch ein paar Gedanken machen wie das automatisiert gehen kann und soll. Was muss man also beachten, dass dies auch in der SPS funktioniert? 

2. Issue: Wie kommt das Frontend in das Gateway? Ich denke da sind wir mit dem Webjar schon relativ weit.

3. Issue: Wie kommt das Gateway auf die OpenShift Plattform. Natürlich kann man das per Hand machen (dafür müsste aber auch dokumentiert werden wie das geht), aber der Anspruch, den wir definiert und kommuniziert haben ist ja ein anderer. Wir wollen automatisiert aus der SPS heraus deployen. Dieses Issue sollte also eine Verbindung zu Issue 1 haben. 

Ich mache diese Issues jetzt einfach mal auf. Sollte das so nicht passen, dann können die ja wieder geschlossen werden :)

**Comment by rowe42** [comment]
Wird geschlossen. Siehe Issues oben.
