### ISSUE TITLE
Liste für Enclosures erstellen

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#146]
Bis auf den Punkt "Objektsuche" ist die Liste für die Keepers so weit, dass man sie auf die anderen Entitäten umsetzen kann. Da die Objektsuche Back- und Frontend betrifft, weise ich die Liste für enclosures trotzdem schon zu, falls für die Verallgemeinerung noch neue Punkte aufkommen.

**Comment by xdoo** [comment]
@ejcsid bevor wir das vervielfältigen hätte ich noch ein paar Fragen bezüglich der Generierbarkeit (mit denen werden wir uns früher oder später beschäftigen müssen - also besser bevor der Code vervielfacht wird :)

https://github.com/xdoo/lhm_animad_admin_html5/blob/7c122a2130be07b73196a7a539c26ed4c3275512/src/animad-keeper/animad-keepers-list.html#L219
Dieses Property gibt es einmal in der Webcomponente und einmal in der Behavior.
https://github.com/xdoo/lhm_animad_admin_html5/blob/7c122a2130be07b73196a7a539c26ed4c3275512/src/behaviors/animad-list-behavior.html#L35

1. Ich denke wir sollten dieses Property nur einmal definieren (aus meiner Sicht in der Behavior). 
2. In der Komponente ist dieses Property befüllt. Woher kommen denn die Informationen? Ziel ist es ja, dass die Webkomponenten zu 100% generiert werden. Mir ist nicht klar, wie diese Infromation generiert werden kann. Aus meiner Sicht sollte die von aussen kommen (z.B. als Array, oder als URL und kann dann nachgeladen werden).

https://github.com/xdoo/lhm_animad_admin_html5/blob/7c122a2130be07b73196a7a539c26ed4c3275512/src/animad-keeper/animad-keepers-list.html#L295

Die Frage von Punkt 2. trifft auch auf die Methode `_useSelectedFilters` zu. Die ist ja komplett auf die Struktur der Filter zugeschnitten. Mir ist nicht klar, wie wir diesen Code generieren können. Zumal da ja auch noch die Implementierung der jeweiligen Filter rein gehört.

https://github.com/xdoo/lhm_animad_admin_html5/blob/7c122a2130be07b73196a7a539c26ed4c3275512/src/animad-keeper/animad-keepers-list.html#L249

Woher weiß denn die Komponente von der `keepers-view`? Die Komponenten können doch in beliebige views eingebettet werden. Würde sich damit dann nicht auch der Pfad ändern?

**Comment by ejcsid** [comment]
Danke für das Review

Zu Frage 1) und 2): Stimmt, das ist ein Hack, der so nicht in die anderen Tabellen rein soll. Und ja die Methode  `_useSelectedFilters(keeper)` muss immer manuell implementiert werden, das geht nicht anders. Ich werde es so umbauen, wie es der Generator erzeugen kann, die Methode ist dann halt leer. Default ist, dass es diese Filter nicht gibt.
Zu 3) (keeepers-view): Werde dies URLs als Parameter überreichen.

**Comment by dragonfly28** [comment]
@ejcsid : wir haben unterschiedliche Darstellungen der generierten Komponenten. Einmal Deine Tabelle erreichbar unter "keepers-view" und zusätzlich die "keepers-formsamples-view" mit den restlichen Komponenten. Bei den animals und enclosures gibt es nur eine View mit allen Komponenten.

Macht es nicht Sinn, alle generierten Komponenten einfach auf eine Seite zu klatschen, beginnend mit der Tabelle und darunter alles andere so wie z.B. bei den Animals? Von mir aus getrennt mit <hr>?

Oder machen wir es bei allen so wie bei den Keepers, also von der 'keepers-view' auf die Tabelle und von dort auf die 'create'- und 'update'-Formulare? Zusätzlich dann jeweils eine Seite '<...>-formsamples' als Anschaumöglichkeit der generierten Komponenten.

**Comment by ejcsid** [comment]
Mein Verständnis ist, dass die untereinander dargestellten Forms nur zur
Anschauung dienen was geht. Das kann man bei den Listen auch machen (es
gibt auch da unterschiedliche Ausprägungen je nachdem wie sie aufgerufen
werden). Aber für den Showcase wird ja eh alles so aufgebaut wie im vaadin
Beispiel.

Am 05.02.2018 4:46 nachm. schrieb "Robert Jasny" <notifications@github.com>:

**Comment by dragonfly28** [comment]
Ich füge dann ganz einfach bei den Komponenten-Listen der Animals und Enclosures ganz oben die Tabelle ein.

**Comment by dragonfly28** [comment]
Wird im Rahmen von Branch _#146 erledigt, ebenso Issues  #168 und #169.

**Comment by dragonfly28** [comment]
gelöst mit #172
