### ISSUE TITLE
Navigation: Kompletten Refresh der Seiten vermeiden

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#147]
Derzeit wird in der Liste mit windows.location = '...' auf das Create- und Edit-Format gewechselt. Dies führt zu einem kompletten Bildschirmaufbau der Seiten. Über this.set('route.path', '...') könnte das geändert werden.

**Comment by dragonfly28** [comment]
Ich habe ein lokales Beispiel, bei dem funktioniert das mit this.set('route.path', '...').
In den Forms muss man dann auch mit app-location und app-route arbeiten, nur in animad-app funktioniert das nicht.
siehe auch #122

**Comment by ejcsid** [comment]
Mit Pull Request #159 behoben.
