### ISSUE TITLE
Formulare in 'Animals' funktionieren nicht

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#149]
Bei mir funktionieren aktuell die Formulare in der Animals View teilweise nicht.
Firefox 58.0:
![screenshot-2018-2-1 animad 1](https://user-images.githubusercontent.com/712911/35675939-355468aa-074a-11e8-9ef9-60610ed965a0.png)

Chrome:
![animad 1](https://user-images.githubusercontent.com/712911/35675996-69d37abc-074a-11e8-8960-e873ca49ff52.png)

**Comment by xdoo** [comment]
Im Inkognitofenster funktioniert es. Deshalb schließe ich dieses Issue, da es nicht auszuschließen ist, dass es ein Chaching Proplem ist.

**Comment by xdoo** [comment]
Sorry - muss nochmal zurück rudern. Im Chrome stimmt das oben gesagte. In Firefox tritt das Problem bei mir auch im privaten Modus auf. Ich mache deshalb das Issue wieder auf.

**Comment by dragonfly28** [comment]
gelöst mit Fix zu #158
