### ISSUE TITLE
Formulare in 'Enclosure' funktionieren nicht

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#150]
Bei mir funktionieren aktuell die Formulare in der Enclosures View teilweise nicht.
Firefox 58.0:
![screenshot-2018-2-1 animad 2](https://user-images.githubusercontent.com/712911/35676045-97c43902-074a-11e8-8fe5-6eb772d0fef0.png)

Chrome:
![animad 2](https://user-images.githubusercontent.com/712911/35676075-b3d401b8-074a-11e8-9fce-6caa965bb5f0.png)

**Comment by xdoo** [comment]
Im Inkognitofenster funktioniert es. Deshalb schließe ich dieses Issue, da es nicht auszuschließen ist, dass es ein Chaching Proplem ist.

**Comment by xdoo** [comment]
Sorry - muss nochmal zurück rudern. Im Chrome stimmt das oben gesagte. In Firefox tritt das Problem bei mir auch im privaten Modus auf. Ich mache deshalb das Issue wieder auf.

**Comment by dragonfly28** [comment]
gelöst mit Fix zu #158
