### ISSUE TITLE
Formulare: Navigation Abbrechen und Speichern Button in allen Formularen

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#154]
Im Moment wechselt die Animal-Form (Create- und Edit) auf die Keepers-Liste beim Klick auf 'Abbrechen' .

Ich dachte, dass die Implementierung des Tickets #128 die Navigation für alle Buttons in allen Formularen umsetzt. Und wenn dann mal alle Listen da sind, sollte natürlich die Animad-Animal-Form auf die Animad-Animal-Liste navigieren.

**Comment by dragonfly28** [comment]
Der Fehler war in der animad-animals-view.html, weil dort
```save-path="/animals-view/"
    cancel-path="/animals-view/"
```
falsch gesetzt waren. Wurde in einem der zahlreichen Fixes der letzten Tage angepasst.
Ich schliesse deshalb dieses Issue.
