### ISSUE TITLE
Heirat Frontend und API Gateway

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#156]
Wie kommt das Frontend in das Gateway? Ich denke da sind wir mit dem Webjar schon relativ weit.

**Comment by xdoo** [comment]
siehe auch #136

**Comment by rowe42** [comment]
Ist schon so im pom.xml realisiert.
Noch ToDo: In einem Wiki-Artikel dokumentieren.

**Comment by rowe42** [comment]
Implementierung ist erfolgt, eingecheckt und gemerged. Wiki-Artikel folgt.

**Comment by rowe42** [comment]
Wiki-Artikel liegt im internen Wiki hier:
.../Java-Architektur/index.php/Heirat_Frontend_und_Backend

Schließe das Issue.
