### ISSUE TITLE
Liste: Suche muss Leerzeichen in den Suchstrings unterstützen

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#173]
Es muss auch eine Suche nach name:"Elephant's Paradise" möglich sein (siehe Enclosures Liste)

**Comment by dragonfly28** [comment]
Achtung, bei der Liste zu den Enclosures geht die Suche auf www.mockable.io!
Hier gibt es nur Antworten zu den Requests:
- http://demo7841195.mockable.io/enclosures/search/findFullTextJunction?q=name:elefantenparadies
- http://demo7841195.mockable.io/enclosures/search/findFullTextJunction?q=""

Der Suchstring nach "name:Elephant's Paradise" sieht aber tatsächlich buggy aus:
.../enclosures/search/findFullTextJunction?q=name:elephant's "paradise"

**Comment by ejcsid** [comment]
Mit Pull Request #176 merged in master.
