### ISSUE TITLE
Liste: Filter-Button mit vorgefertigter Suche (wie bei Github)

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#181]
Idee: Fachbereich definiert "typische Suchen", die werden in einem Dropdown-Button angeboten und werden dann in das Suchfeld eingebracht.

**Comment by rowe42** [comment]
Ggf. kann @dragonfly28 das übernehmen? @ejcsid stimmt mit ihm ab.

**Comment by rowe42** [comment]
Idee: "Is-Alive" bei den Animals.

**Comment by ejcsid** [comment]
Als Beispiel sollte bei den Animals die Suche / das Filtern nach "is:alive" gehen.

**Comment by dragonfly28** [comment]
Vorschlag: 
- ich denke, das ist kein Thema für die Modellierung sondern Konfiguration
- wir generieren ein leeres JSON-File "filters.json" in einem Verzeichnis  "config" welches vom "animad-list-header.html" eingelesen wird und aus dem die Vorschläge für die Filter gelesen werden
- das JSON-File kann vom Entwickler angepasst werden und wird nicht überschrieben

**Comment by ejcsid** [comment]
Nicht vergessen: Die Texte müssen lokalisiert angezeigt werden.

**Comment by rowe42** [comment]
@ejcsid In Abstimmung mit Dirk habe ich das jetzt "fertig" implementiert, wobei ich einige Vereinfachungen angesetzt habe:
- es kann nur jeweils ein vorgefertigter Filter gewählt werden (keine Kombination) --> wie bei Github
- die Anwahl eines Filters löscht den aktuellen Suchtext
- ein Zurücksetzen des Filters kann über Klick auf das "X" neben dem Suchfeld erreicht werden; alternativ kann natürlich auch der Suchtext verändert werden (der Filter setzt sich dann aber nicht zurück)
- die Filter kommen NICHT aus einem JSON-File, sondern nach wie vor aus einem Feld, das in der jeweiligen View (hier: animad-animals-view) definiert wird und Einträge im locales.json benötigt.

Alles in allem deckt es aber ziemlich genau die Funktionalität ab, die man auch bei Github findet, und so wollte es @Baumfrosch ja haben.

Ich würde das Issue jetzt schließen. Du kannst es aber gern wieder aufmachen, wenn du doch deine Version umsetzen möchtest (bitte aber beachten, dass ich auch noch die Übersetzung der Suchbegriffe ("Elefant"-->"Elephant") implementiert habe; die solltest du übernehmen.

Ich habe die Umsetzung im neuen Branch _#181_rowe42 gemacht, so dass deine Version noch unverändert in deinem Branch enthalten ist.
