### ISSUE TITLE
Zwei Tabellen zur selben Entität auf der selben Seite führt zu filtern in beiden Listen

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#195]
Zu beobachen in der aktuellen Animals-Seite. Diese enthält zwei Tabellen, eine im Search- und eine im Filter-Modus. Wenn man nun in der Filter-Tabelle (die untere) filtert, dann filtert sich automatisch auch die obere Tabelle.

**Comment by ejcsid** [comment]
Ich kann mir nicht vorstellen, dass es eine Fachanwendung gibt, die 2 Tabellen mit den gleichen Datensätzen auf einer Seite anzeigt.
