### ISSUE TITLE
Logout-Button

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#197]
Wenn man die Animad-Applikation aufruft und nicht angemeldet ist, wird man automatisch zu KeyCloak zum Login geschickt. Einen Logout muss man aber aktiv anstoßen. Dazu braucht es einen Button irgendwo im Menü (z.B. rechts oben).

Meiner Meinung nach sollte der Logout nur ein lokales Logout durchführen, also die Session der Animad-App zerstören und auf eine neutrale ungesicherte Seite leiten. Damit bliebe die Session im KeyCloak bestehen. Dies wird für echtes Single-Sign-On benötigt, führt aber dazu, dass ein erneutes Login ganz ohne Passwort-Eingabe verlaufen würde (man bekommt KeyCloak dann gar nicht mehr zu Gesicht).

**Comment by ejcsid** [comment]
Auf Milestone 1, da das schon implementiert ist - richtig? Sonst wäre das auch was für Milestone 2

**Comment by rowe42** [comment]
Richtig, kommt demnächst der PR

**Comment by rowe42** [comment]
Gefixt. In Master. Schließe das Issue.

z.K. @ejcsid @xdoo @dragonfly28 @Baumfrosch
