### ISSUE TITLE
DB-Tabellen doppelt generiert bei Relationen

### ISSUE THREAD

**Issue by dragonfly28** [xdoo/lhm_animad_admin_html5#206]
In unserem Modell werden für many-to-many Relationen jeweils zwei DB-Tabellen generiert wobei eine davon überflüssig erscheint. Beispiel im Modell Animal-Keeper:
```
entity animal {
       ...
        keeperList manyToMany keeper;
        ...
}
```
daraus werden zwei DB-Tabellen erzeugt:
```
ANIMAL_KEEPERLIST
ANIMAL_KEEPER_LIST
```
Erstere Tabelle bleibt immer leer, zweitere wird gefüllt beim Anlegen von Relationen.

Ich vermute einen Bug im Generator bzw. eine nicht dokumentierte Namenskonvention für die Benennung der Relationen.

**Comment by ejcsid** [comment]
In der neuen Barrakuda-Version schon behoben
