### ISSUE TITLE
Platzierung von Speichern-Buttons in Formularen

### ISSUE THREAD

**Issue by olympialice** [xdoo/lhm_animad_admin_html5#207]
Der Speichern-Button bzw. die primäre Aktion sollte in Formularen ganz links platziert werden (siehe auch Abschnitt "Recommended button placement in Forms" in [Material Design](https://material.io/guidelines/components/buttons.html#buttons-usage)) Danach kommt der Abbrechen Button (falls benötigt). Als sekundäre Aktion könnte der Abbrechen-Button auch als Flat Button dargestellt werden (siehe auch [Material Design](https://material.io/guidelines/components/buttons.html#buttons-flat-buttons))

**Comment by eidottermihi** [comment]
@olympialice Habe das mal umgesetzt (siehe Screenshot). Damit wäre nun die Hauptaktion links und "raised", die sekundären Aktionen daneben (aber trotzdem linksbündig) und "flat".

Ok?

![grafik](https://user-images.githubusercontent.com/2780736/37719210-c7eda9b0-2d24-11e8-9b2d-3fb306785aba.png)

**Comment by FabianWilms** [comment]
Das ist jetzt zwar meckern auf hohem Niveau, aber könnten wir für den Speichern-Button auch das iron-icon `save` (eine Diskette) benutzen? Wir "versenden" ja nichts, sondern speichern nur.

**Comment by eidottermihi** [comment]
Hast Recht, passe ich in diesem Zuge mit an.
