### ISSUE TITLE
Platzierung von Buttons in Dialogen

### ISSUE THREAD

**Issue by olympialice** [xdoo/lhm_animad_admin_html5#208]
Für alle Dialoge in Referenzarchitektur zu prüfen bzw. zu ändern: Im Gegensatz zu Formularen wird in Dialogen empfohlen Buttons rechts zu platzieren. Siehe auch "Recommended button placement in Standard dialogs" von [Material Design](https://material.io/guidelines/components/buttons.html#buttons-usage) 

Generell gilt in Dialogen: Button alignment on screen: right
Place the affirmative button on the right, the dismissive button on the left.

Ausnahme: Löschen-Buttons sollten NICHT unten rechts gesetzt werden, da dort der Nutzer in Dialogen als erstes hinklicken wird. Hier würde sich die Reihenfolge "Löschen"-"Abbrechen" anbieten.

**Comment by rowe42** [comment]
@olympialice was in unserer zoo Anwendung ist denn ein Dialog und was ein Formular?

**Comment by dragonfly28** [comment]
Formular: Update/Create und Liste
Dialog: z.B. das modale Fenster beim Löschen einer Entität aus der Liste "Wollen Sie wirklich löschen?"

**Comment by rowe42** [comment]
Jetzt in master. Schließe das Issue.
