### ISSUE TITLE
Markierung von Navigationseinträgen wenn geklickt

### ISSUE THREAD

**Issue by olympialice** [xdoo/lhm_animad_admin_html5#209]
Derzeit sieht der Benutzer nicht, innerhalb welches Navigationseintrages der linken Navigationsleiste der Zoo-Anwendung er sich befindet, wenn er einen Eintrag angeklickt hat. Der Navigationseintrag links sollte farblich geändert/hinterlegt werden, damit dem Benutzer zu jeder Zeit klar ist, wo er sich befindet.

**Comment by Baumfrosch** [comment]
Sagt MD etwas, wie die farbliche Markierung aussehen soll?

**Comment by xdoo** [comment]
Ja: https://material.io/guidelines/style/color.html#color-color-system

**Comment by rowe42** [comment]
Habe das im Zuge meiner Arbeit an den Security-Tags gefixt und in Branch _#202 eingecheckt. Habe mich aber ehrlicherweise nicht um die Farben gekümmert - d.h. da muss man ggf. noch was nachziehen, wenn es nicht MD-konform ist.

PR kommt im Laufe des Montag.

**Comment by rowe42** [comment]
Jetzt nach Master gemerged. Schließe das Issue. Bitte neues öffnen, wenn die Farben nicht zu MD passen @olympialice .

**Comment by rowe42** [comment]
z.K. @xdoo @Baumfrosch @dragonfly28 @ejcsid
