### ISSUE TITLE
Liste: Letzte Suchanfragen bei Eingabe in Such-Feld anzeigen

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#217]
Entstanden aus Ticket #205.

- Die Anzahl der letzten Suchangaben sollte konfigurierbar sein, Standard: die letzten 5?

**Comment by rowe42** [comment]
Aus Gespräch mit @Baumfrosch: Ist wichtig, soll in Meilenstein 3 gemacht werden.
@ejcsid Kannst du dir das ansehen? Die Suchen sollten im Backend gespeichert werden (nicht in einem Cookie o.ä.).
**Vorschlag:** Wir erweitern hierfür den User-Service, dann müssen wir keinen eigenen MS dafür einführen (allerdings braucht der User-Service dafür eine DB, die er heute noch nicht hat). Bitte die Architektur hierfür mal in der AG zur Diskussion stellen.

**Comment by rowe42** [comment]
@ejcsid 
Ist jetzt im user-service implementiert (@xdoo sorry, aus Versehen gleich in den master eingecheckt). 

Funktionalität ist wie folgt:

**1. Neue Suche anlegen**
URL: `POST http://localhost:8082/api/user_service/customsearches/replaceOldestSearchForCurrentUser`
Body: 
```
{
  "componentName": "component",
  "searchName": "my first search",
  "search": "vorname:hugo"
}
```
Hier wird so lange eine neue Suche für den aktuellen User angelegt, bis die im Backend konfigurierte maximale Anzahl gespeicherter Suchen pro User erreicht ist. Dann wird die älteste der gespeicherten Suche gelöscht und die neue (mit Timestamp "now") angelegt.

Wenn man den User-Service mit Security startet, wird der Username des aktuell angemeldeten Users aus dem Access-Token geparst. Wenn man No-Security verwendet, wird hardcoded "animad_admin" als User gesetzt.

**Hinweis:** Im JSON kann man zwar "userName" als Feld schicken. Es wird aber immer überschrieben.

**2. Bestehende Suchen abrufen**
URL: `GET http://localhost:8082/api/user_service/customsearches/searchesForCurrentUser?componentName=component`
wobei der ComponentName die Komponente im Frontend ist, um die es geht, also bspw. eine Table. Vorschlag: Wir setzen im Frontend bei `*-table` das Attribut `name` auf einen eindeutigen Wert und verwenden den dann an dieser Stelle. Auf diese Weise kann es innerhalb einer Anwendung mehrere Tabellen der selben Entität geben, die aber unterschiedliche Suchen gespeichert haben (oder man setzt das Attribut eben auf den gleichen Wert, wenn man die gleichen Suchen möchte).

Das Ergebnis sieht so aus:
[ {
  "oid" : "cbe50046-757a-4d07-9bde-7bd879d06724",
  "userName" : "animad_admin",
  "componentName" : "component",
  "searchName" : "my first search",
  "search" : "vorname:hugo",
  "lastUpdated" : "15:50:45.653"
} ]


Ich habe außerdem noch die Methode
URL: `POST http://localhost:8082/api/user_service/customsearches/createTestSearches`
erstellt, mit der man sich 5 Suchen anlegen kann (allerdings mit unsinnigem Inhalt, das müsstest du noch ein bisschen für deine Zwecke anpassen).


@ejcsid Könntest du an dieser Stelle übernehmen und das Frontend erweitern? Wie besprochen ungefähr so:
- Neben das Suchfeld in der Tabelle kommt ein Sternchen-Icon
- Wenn man darauf klickt, öffnet sich ein kleines modales Fenster, in das man den Namen der Suche eintippen muss
- Nach abschicken des modalen Fensters wird die Suche mit Methode 1) von oben ans Backend geschickt und dort gespeichert.
- Im bereits bestehenden Predefined-Searches-Dropdown werden die vom User gespeicherten Suchen mit Methode 2) abgerufen und mit aufgenommen - am besten sogar über den vorgefertigten, da diese Suche ja vom User selbst personalisiert wurden und damit "mehr wert sind".
- Denk dran, dass nach dem Abschicken einer neuen Suche ans Backend das Dropdown aktualisiert werden muss (aufgrund der Asynchronität darf das erst erfolgen, wenn der Backend-Call durchgeführt wurde).

@Baumfrosch zur Info

**Comment by rowe42** [comment]
Ist jetzt im Master. Habe mich allerdings gefragt, warum wir es nicht auch für die Liste anbieten? Was spricht da dagegen? @ejcsid

**Comment by ejcsid** [comment]
Bei den Keepers wird bei der Liste das Filter-Feld angezeigt und nicht das Suche-Feld, d.h. dort wird gar die Suchanfrage beim Backend nicht gefiltert, sondern immer alle Datensätze geholt. Folglich kann da keine Suche gespeichert werden. Wenn wir eine Liste mit Suche-Feld haben, dann spricht auch nichts dagegen dort die Suchen zu speichern.

**Comment by ejcsid** [comment]
Ich schließe das Issue, da der Code gemerged ist. Offene Punkte können in neuen issues bearbeitet werden.
