### ISSUE TITLE
Backend Datenbank-Constraints werden im Frontend nicht verständlich interpretiert

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#218]
Beispiel:
Ein Gehege anlegen und dabei ein Tier verwenden, das bereits einem anderen Gehege zugeordnet ist.
Im Backend wird eine Datenbank-Bedingung verletzt. Im Frontend wird ein Fehlercode 409 ausgegeben, ohne weitere Erklärung. Erst nach Analyse des Backend-Logs versteht man, warum das nicht ging.

Erwartet: Eine Fehlermeldung, die den Sachverhalt verständlich erkärt.

@xdoo @dragonfly28 @ejcsid @Baumfrosch

**Comment by Baumfrosch** [comment]
Setzen wir DB-Constraints ein also RI-Checks im DBMS? In meiner Jugend war das verboten. Wer soll das noch verstehen? Was passiert beim Wechsel der DB?

**Comment by Dr-Thomas-Tensi** [comment]
Ich bin nicht @Baumfrosch s Meinung: RI-Checks im DBMS sind auf jeden Fall eine sinnvolle Dokumentation. Und bei einem DB-Wechsel werden sie halt in der Ziel-DB nachgebaut.
Wer sagt denn, dass nicht irgendein Hugo direkt auf die Datenbank zugreift...
Warum wird denn überhaupt die Integritätsbedingung der DB verletzt? Der Anwendungskern muss doch sicherstellen, dass die Regeln eingehalten werden, oder?

**Comment by Baumfrosch** [comment]
OK, ich habe mich unglücklich ausgedrückt. Verboten ist es , sich auf RI-Checks in der DB zu verlassen. Die Checks werden auf jeden Fall im Anwendungskern geprüft.

**Comment by ejcsid** [comment]
Beschluss aus der RefArch: Für Milestone 2 sollen die 4*-Nummern in locales.json Fehlertexte bekommen.

Die Vorschläge von @xdoo kommen in ein eigenes Ticket für Milestone 3.

**Comment by rowe42** [comment]
4*-Nummern haben nun eigene Fehlertexte im locales.json. Schließe das Issue.
