### ISSUE TITLE
Packagenamen und GroupId für authorisationLib umbenennen

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#222]
Die Bibliothek authorisationLib verwendet im Packagenamen und in der GroupId "referenzarchitektur". Das sollte wie folgt umbenannt werden:

Package de.muenchen.referenzarchitektur.authorisationLib; in de.muenchen.commons.authorisation;
GroupId de.muenchen.referenzarchitektur in de.muenchen.commons.authorisation

**Comment by rowe42** [comment]
Erledigt. Schließe das Issue.
