### ISSUE TITLE
DTOs als Parameter oder Rückgabewert von BusinessActions

### ISSUE THREAD

**Issue by a52team** [xdoo/lhm_animad_admin_html5#224]
Zusätzlich zu bestehenden Datentypen und Entities können auch DTOs definiert werden, welche als Parameter bzw. Rückgabetypen in BusinessActions verwendet werden können.

Für die Darstellung der DTOs gibt es noch kein Muster.

**Comment by a52team** [comment]
Beispiel:

    dto theDto1 {
        ...
    }
    
    dto theDto2 {
        attr1 theInteger "4";
        ...
    }
    
    businessAction getDto{
          purpose "Dto in param and return value";
          given theDtoasParam theDto1;
          given theNumbers listOf theInteger;
          then theDto2;
    }

**Comment by xdoo** [comment]
Wo liegt der Unterschied zu #225 ?

**Comment by a52team** [comment]
Grundsätzlich besteht kein Unterschied zu #225. Die Dsl bietet mit DTOs die Möglichkeit, fachlich zusammengehörige Informationen die nicht mit Entitäten oder ValueObjects dargestellt werden, zu bündeln bzw. zu aggregieren. Diese können dann von BusinessActions als Parameter erwartet oder zurückgegeben werden.


    public class GetDto_BusinessActionParameters {
            ...
	    private java.util.List<TheDto1_> theDtoasParamList;
	    private TheDto1_ theDtoasParam;
            ...
    }

**Comment by xdoo** [comment]
Sollten wir dann nicht ein Issue schließen, wenn kein Unterschied besteht? Im besten Fall dieses.

**Comment by a52team** [comment]
Ja, können wir gerne machen.
