### ISSUE TITLE
Maßeinheiten bei Attributen

### ISSUE THREAD

**Issue by a52team** [xdoo/lhm_animad_admin_html5#226]
Für Attribute können in der Barrakuda-Sprache keine Maßeinheiten definiert werden.

Der Ausdruck <div slot="suffix">KG</div> bei Animal::weight ist somit nicht generierbar.

**Comment by xdoo** [comment]
Es würde die Sache deutlich vereinfachen, wenn du den Code, den du meinst aus referenzieren würdest.

**Comment by a52team** [comment]
Beispiel:

https://github.com/xdoo/lhm_animad_admin_html5/blob/1b655d956ee81e948ad00a78f1f1e1e2f9bd0fa5/src/animad-animal/animad-animal-form.html#L120

**Comment by xdoo** [comment]
Ja, das muss raus. Hast du noch weitere Stellen gefunden?

**Comment by a52team** [comment]
In der Kürze bis jetzt noch nicht.

**Comment by rowe42** [comment]
Ich machs weg ;-)

**Comment by rowe42** [comment]
Gefixt in Branch _#233

**Comment by rowe42** [comment]
Jetzt in master. Schließe das Issue.
