### ISSUE TITLE
List Komponente

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#229]
Ich denke wir benötigen neben der klassischen Tabelle eine Liste zur Darstellung von Arrays / Listen. Aus meiner Sicht sprechen folgende Gründe dafür:

- In einer Liste können die Daten weniger statisch angeordnet werden als in einer Tabelle. Die Freiheitsgrade in der Darstellung sind deutlich höher.
- Listen sind per se responsive. Tabellen haben hier wegen ihrer statischen Spalten / Zeilenstruktur Probleme.
- In Listen können grafische Elemente Icons / Avatars aufgenommen werden. Dies ermöglicht es einem Nutzer ohne zu lesen bestimmte Informationen zu bekommen. Beispiel: Ich habe zu einem Fall n unterschiedliche Aktionen wie Benachrichtigung schreiben, Hausbesuch, etc. Jede dieser Aktionen hat ihr eigenes Icon. So kann der Sachbearbeiter - wie in einem Karteikasten (dort haben die bei BeZweck unterschiedlich farbige Karten) - beispielsweise den letzten Hausbesuch heraus suchen ohne lesen zu müssen. 
- In einer Liste kann ich unterschiedliche Objekte darstellen (die müssen natürlich eine Überschneidung bei den dargestellten Attributen haben).

So könnte das aussehen:

![screenshot-2018-2-28 polymerelements paper-item v2 1 0](https://user-images.githubusercontent.com/712911/36788952-2ead9ef8-1c90-11e8-9f91-9cfe75f196ef.png)

https://www.webcomponents.org/element/PolymerElements/paper-item

**Comment by rowe42** [comment]
Wo im Zoo Beispiel könnte man das anwenden? Wäre eine Liste und unsere aktuelle Tabelle 1:1 austauschbar? Lässt sich eine Liste auch filtern? Lässt sich das Ergebnis einer Suche auch alternativ als Liste darstellen?

**Comment by xdoo** [comment]
> Wo im Zoo Beispiel könnte man das anwenden?
Überall wo man mehr als einen Datensatz anzeigen will.

> Wäre eine Liste und unsere aktuelle Tabelle 1:1 austauschbar?
Grundsätzlich ja, da sie ja beide Listen von Objekten anzeigen. Auf der anderen Seite nein, weil sie einen unterschiedlichen Funktionsumfang bieten. Sowohl eine Tabelle, als auch eine Liste hat ihre Einsatzszenarien. Ich hatte versucht das oben darzustellen.

> Lässt sich eine Liste auch filtern?
Grundsätzlich ja (wenn man das will - Listen will man auch einsetzen, weil sie etwas einfacher gestrickt sind und dadurch die Komplexität reduzieren. Die erhöht man natürlich wieder, wenn man zusätzliche Funktionalität wie Filter verwendet.). Ich lehne mich mal aus dem Fenster und behaupte, dass man die Filter, die in der Tabelle verwendet werden auch hier zum Einsatz bringen kann :) Der Filtermechanismus basiert ja auf der Datenbasis und nicht auf der grafischen Komponente.

> Lässt sich das Ergebnis einer Suche auch alternativ als Liste darstellen?
Ja. Das ist aus meiner Sicht sogar der Normalfall. Das Ergebnis von Google, Bing usw. ist jeweils eine Liste und keine Tabelle.

**Comment by xdoo** [comment]
Übrigens: Wer sich die Komponenten in der MD Spec anschaut (https://material.io/guidelines/components/) wird dort keine Tabelle finden. Aber sehr wohl eine Listen Komponente: https://material.io/guidelines/components/lists.html#lists-behavior

Dort steht auch etwas zum Filtern und Sortieren.

**Comment by rowe42** [comment]
Ich habe mal einen ersten Aufschlag als Vorschlag implementiert. Da ich sehr starke Überschneidung in der aktuellen Tabelle sehe, habe ich es dort eingebaut (die Komponente heißt ja sogar schon "animad-xxx-list"). Lässt sich aktivieren, indem `display-type='list'` in der Komponente gesetzt wird.
Habe es in Branch _#235 eingecheckt und dort (nur) bei den Keepers implementiert. Sieht so aus:
![image](https://user-images.githubusercontent.com/25983841/36950840-416758c6-1ffc-11e8-8825-15a72ff090b7.png)

@xdoo @ejcsid Was meint ihr? Wollen wir das so machen?

**Comment by xdoo** [comment]
Mir gefällts. Unabhängig davon, dass es eine Meta Komponente gibt, die Suche / Liste / Tabelle vereinigt sollte das schon eine eigene Komponente sein.

**Comment by rowe42** [comment]
OK, dann lasse ich das Issue noch offen und ergänze noch die folgenden Punkte:
- Wrapper-Komponenten, die jeweils eine Liste oder Tabelle mit Standard-Einstellungen (z.B. bei Liste = loadCompleteData) bewirken
- eine Wahlmöglichkeit, ob man Icons will (im Beispiel oben macht das Icon eigentlich wenig Sinn, da es immer das Keeper-Icon ist; wenn wir später mal eine Liste eines Obertyps haben, der auf versch. Untertypen vererbst machen die dann unterschiedlichen Icons wieder sinn)

**Comment by rowe42** [comment]
ListComponent jetzt wie oben erweitert, die Komponenten heißen nun
- animad-keepers-list
- animad-keepers-table
und basieren beide auf animad-keepers-generic-list.

Außerdem das Flag `"show-icons"` ergänzt.

Ist in master, schließe das Issue.
