### ISSUE TITLE
Default Value für service.configuration.maxSearchResults

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#240]
Die Anwendung fährt sonst nicht hoch, wenn der Wert in der Konfigruation nicht vorhanden ist.

**Comment by ejcsid** [comment]
In den zusammengeführten Sourcen ist das bereits drin.

**Comment by rowe42** [comment]
Wird wie vereinbart geschlossen, nachdem Pull Request admin-service/#21 durch ist.
