### ISSUE TITLE
View-Icons den Views zuordnen

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#243]
Wir verwenden derzeit je View ein Icon, das gleichzeitig auch das Icon der zugehörigen Entität ist. Da aber Views nicht zwangläufig nur eine Entität verwenden, muss man das abtrennen und für die Views eigene Icons verwenden (die dann aber wieder gleich dem Entitäts-Icon sind).

**Comment by xdoo** [comment]
Ich würde die einfach weg machen. Die sind nur drin weil ich sie irgendwann rein gemacht habe :)

**Comment by rowe42** [comment]
Aber ist doch schick. Ich mach das einfach beim nächsten merge mit rein, ist ja kein großes Thema.

**Comment by rowe42** [comment]
Gefixt in Branch _#244 (html5)

**Comment by rowe42** [comment]
Gibt jetzt eigene View-Icons. Ist in Master. Schließe das Issue.
