### ISSUE TITLE
CascadeTypes anpassen

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#248]
Aktuell werden bei `ManyTo...` to Beziehungen in den Entitäten folgende CascadeTypes heraus generiert:
```java
@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
```
Das führt in bestimmten Konstellationen zu Fehlern und ist vermutlich auch völlig unnötig, da die `save` Methode von Spring Data Jpa selbständig entscheidet, ob sie `merge` oder `persist` aufrufen muss.

Die gesamte Diskussion über dieses Problem ist unter #212 zu finden.

**Comment by rowe42** [comment]
Entfernt und eingecheckt in Branch _#212 in admin_service, siehe PR https://github.com/xdoo/lhm_animad_admin_service/pull/19

**Comment by rowe42** [comment]
Nach master gemerged. Schließe das Issue.
