### ISSUE TITLE
Maven-Project-Version im Footer

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#254]
@eidottermihi @xdoo 

Dieses Issue ist zur Diskussion der verschiedenen Optionen, die Maven-Project-Version im HTML5 darzustellen (für Testing etc.)

**Comment by rowe42** [comment]
Vorschlag: Verwenden wir doch das Maven-Filtering.
Siehe hier: https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html
Bei Spring-Boot-Projects etwas abgewandelt: https://stackoverflow.com/questions/36501017/maven-resource-filtering-not-working-because-of-spring-boot-dependency

Ich habe es mal kurz ausprobiert: Wenn ich eine Datei `version.txt` z.B. nach `/src` lege mit folgendem Inhalt:
```
Version: @project.version@
```

und die pom.xml so verändere:
```
        <resources>
            <resource>
                <directory>build/es5-bundled</directory>
                <targetPath>static</targetPath>
		<filtering>true</filtering>
            </resource>
        </resources>
```
(neu ist die Zeile mit dem filtering)

dann haben wir im fertigen Build an der Stelle `/src` eine Datei `version.txt` mit folgendem Inhalt:
```
Version: 0.0.1-SNAPSHOT
```

Man kann sich nun einen guten Platz überlegen, wo man das platziert. Entweder man macht einen neuen Footer-Tag in dem der Inhalt einer solchen Datei ausgegeben wird. Oder man nimmt den Platzhalter direkt in die locales.json auf und gibt sie einfach im Footer aus (dann kann man noch sehr schön sprachabhängig die Struktur verändern).

Was meint ihr? Wäre das eine valide Lösung? Wäre zumindest sehr einfach...

@ejcsid @dragonfly28

**Comment by xdoo** [comment]
Die Diskussion sollten wir in #255 führen. Habe alles rüber kopiert. Dieses Issue schließe ich.

**Comment by rowe42** [comment]
OK, das hat sich wohl überschnitten, dass wir die Issues angelegt haben.
