### ISSUE TITLE
Date-Felder ohne Validierung

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#256]
Im Backend werden Input-Felder vom Type Date entsprechend validiert, wenn sie in der DSL so festgelegt wurden, z.B.
```
customTimeType pastDate inThePast date;
```

Im aktuellen Frontend haben wir dafür bisher keine Validierung eingebaut. 
Analog zu unseren anderen Validierungen sollte hier auch sofort beim Verlassen des Felds ein Fehlertext angezeigt werden, wenn man im Beispiel oben ein Datum in der Zukunft eingegeben hat.

@xdoo   @ejcsid  @dragonfly28

**Comment by xdoo** [comment]
Ja. Das geht uns allgemein noch ab. Wir haben derzeit nicht alle Attributtypen und auch nicht alle Ausprägungen dieser Typen als Felder in den Formularen implementiert.

**Comment by eidottermihi** [comment]
@rowe42 Reicht es, wenn wir diese clientseitige Validierung nur für das `paper-input` machen?

So wie ich #7 verstehe, ist eh geplant, den vaadin-date-picker über kurz oder lang rauszuwerfen. Ansonsten müsste ich versuchen, in `animad-date-input` eine Custom Logik zu bauen, die sowohl für das Vaadin-Date-Picker-Element als auch paper-input Element funktioniert.

Wenn wir in Zukunft nur `paper-input` verwenden, könnte ich das schön über [PolymerElements/iron-validator-behavior](https://www.webcomponents.org/element/PolymerElements/iron-validator-behavior) lösen.

**Comment by rowe42** [comment]
Ja mach es nur über paper input. Wenn wir das vaadin Ding wirklich länger und auch produktiv einsetzen wollen müssen wir das dann eben nachrüsten.
Kannst ja ein separates issue dafür aufmachen.

**Comment by eidottermihi** [comment]
War nun doch nicht so kompliziert wie auf den ersten Blick gedacht.

#274 verwendet jetzt einfach die `min` bzw. `max` Properties von `paper-input` bzw. `vaadin-date-picker`. Die Werte für min und max werden basierend auf der Property `validation-type` von `animad-date-input` berechnet.
