### ISSUE TITLE
Mehrfaches Hinzufügen von ManyToMany-Relationen verhindern, wenn Relation bereits vorhanden ist

### ISSUE THREAD

**Issue by dragonfly28** [xdoo/lhm_animad_admin_html5#273]
siehe auch #269 

Bei den Animals kann ein Wärter mehrfach als Relation angegeben werden; die Relation ist hier ManyToMany, was heissen sollte, dass ein Wärter mehrere Tiere bzw. ein Tier mehrere Wärter haben darf. Fachlich falsch ist hier aber, wenn ein Tier denselben Wärter mehrfach hat.
Nachdem das Backend-seitig technisch aber möglich ist,habe ich dieses issue als enhancement eingestellt.

![grafik](https://user-images.githubusercontent.com/13017087/37775923-7f473e90-2de4-11e8-905c-e19a776c7d24.png)

**Comment by Dr-Thomas-Tensi** [comment]
In der UML wäre das eine Annotation an der Beziehung, ob sie eine Menge oder Liste ist. Damit ist klar, ob eine Mehrfachzuordnung verboten oder erlaubt ist.

**Comment by xdoo** [comment]
This issue was moved to xdoo/move_issues#2
