### ISSUE TITLE
De-Selektion eines Filters im Dropdown

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#278]
Derzeit kann eine Filter-Selektion im Dropdown nur über den Suche-Lösch-Button de-selektiert werden. Beit github kann die Filter-Selektion gelöscht werden, die Eingabe im Suche-Feld entspricht dann wieder der Vorbelegung.

**Comment by rowe42** [comment]
Nach Master gemerged. Schließe das Issue.
