### ISSUE TITLE
Filter-Dropdown im Mozill überlagert durch Menü

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#279]
Im Mozilla (getestet mit Version 59.0.1) wird das Filter-Dropdown durch das Menü auf der linken Seite überlagert:

![grafik](https://user-images.githubusercontent.com/33521006/37898845-2cedd830-30ea-11e8-8d76-708837e31b93.png)

**Comment by rowe42** [comment]
Merged nach master. Schließe das Issue.
