### ISSUE TITLE
Anwendung macht Probleme in Firefox (auch 57)

### ISSUE THREAD

**Issue by FabianWilms** [xdoo/lhm_animad_admin_html5#28]
Beim öffnen der Seite taucht folgende Fehlermeldung in der Konsole auf:

```
[...]
TypeError: script is null
TypeError: Polymer is not a function
TypeError: Polymer is not a function
TypeError: Polymer is not a function
TypeError: Polymer is not a function
TypeError: Polymer is not a function
TypeError: Polymer is not a function
TypeError: Polymer is not a function
TypeError: Super expression must either be null or a function, not undefined
[...]
```

Das Problem ist bekannt: https://github.com/Polymer/polymer-cli/issues/905

Lösung:

```polymer.json
{
  [...]
  "builds": [
    {
      "bundle": {
        "excludes": ["bower_components/webcomponentsjs/webcomponents-loader.js"]
      }
      [...]
    }
  ]
  [...]
  }
}
```

**Comment by xdoo** [comment]
Kannst du es fixen und einen Pullrequest machen? :)

**Comment by xdoo** [comment]
Das Verhalten kann ich weder in Firefox 57.0.1 (64-bit) noch in Chrome Version 62.0.3202.94 (Official Build) (64-bit) reproduzieren, wenn ich die Anwendung über `polymer serve` lokal laufen lasse. Bei mir tritt es aktuell nur auf, wenn die Anwendung gebaut und deployed wurde.

**Comment by peter-mueller** [comment]
Ich glaube wir hatten das Problem nach dem Bauen beim Mobilen Piloten in der polymer.json mit den extraDependencies gefixt:

https://gitp001.srv.ha3.dir.muenchen.de/p.mueller/mobilerpilot/blob/master/webapp/polymer.json#L10

```


{
  "entrypoint": "index.html",
  "shell": "src/zweck-app.html",
  "sources": [ ...
  ],
  "extraDependencies": [
    "bower_components/webcomponentsjs/*"
  ],
  "lint": {
    "rules": ["polymer-2-hybrid"]
  },
  "builds": [ ...
  ]
}


```

Dann lädt die Anwendung allerdings überall ein wenig langsamer, weil das script nicht inline genommen wird.

**Comment by FabianWilms** [comment]
Das tritt nur auf wenn man https://xdoo.github.io/lhm_animad_admin_html5/ aufruft (wo die gebaute Version liegt). Lokal habe ich es bisher nicht probiert.

**Comment by xdoo** [comment]
@peter-mueller auf das Repo hinter dem link habe ich keinen Zugriff, deshalb muss ich blöd nachfragen: Habt ihr dann unter 'builds' webcomponents-loader.js auch excluded? Ansonsten hätt ihr das ja zweimal.

**Comment by xdoo** [comment]
@FabianWilms weißt du ob das ein generelles Problem ist, oder nur auf github-pages auftritt?

**Comment by peter-mueller** [comment]
Mehr als diese Datei haben wir nicht konfiguriert:

polymer.json
```
{
  "entrypoint": "index.html",
  "shell": "src/zweck-app.html",
  "sources": [
    "src/**/*",
    "data/**/*",
    "images/**/*",
    "bower.json"
  ],
  "extraDependencies": [
    "bower_components/webcomponentsjs/*"
  ],
  "lint": {
    "rules": ["polymer-2-hybrid"]
  },
  "builds": [
    {
      "preset": "es5-bundled"
    },
    {
      "preset": "es6-unbundled"
    },
    {
      "preset": "es6-bundled"
    }
  ]
```

**Comment by FabianWilms** [comment]
Das Ergebnis von beiden Wegen ist das gleiche. Einmal sagst du dem Polymer CLI, dass er webcomponents.js nicht "inlinen" soll, bei der anderen Lösung wiurd zusätzlich neben dem inline webcomponents.js noch die Dependency ein zweites mal auf dem Webserver mit hochgeladen, damit die anderen Browser das auflösen können.

**Comment by xdoo** [comment]
Da wir primär Firefox verwenden würde es doch Sinn machen das gar nicht mehr inline auszuliefern. Wenn ich es richtig verstanden habe, dann hat damit der FF doppelten Ladeaufwand, oder?

**Comment by xdoo** [comment]
Peters Lösung funktioniert bei Fabi nicht :)

**Comment by peter-mueller** [comment]
@FabianWilms 

Bitte mal folgende Seite testen: https://peter-mueller.github.io/knocklock/

**Comment by FabianWilms** [comment]
@peter-mueller funktioniert!

**Comment by FabianWilms** [comment]
Doku: Lokal ausgeführtes `polymer build` und danach Webserver unter `build/es5-bundled` gestartet: Keine Probleme in den oben genannten Browsern. Scheint also nur in Kombination mit Github Pages Probleme zu machen.

**Comment by FabianWilms** [comment]
Doku: Zum nachstellen des Problems

1. `polymer build`
2. `mkdir ~/tmp && cd ~/tmp && mkdir lhm_animad_admin_html5`
3. `cp -a [...]/lhm_animad_admin_html5/build/es5-bundled/. ~/tmp//lhm_animad_admin_html5/`
4. `cd ~/tmp`
5. `python -m SimpleHTTPServer 8080 &`
6. Browser öffnen unter http://localhost:8080/lhm_animad_admin_html5/

Wenn die Seite dennoch angezeigt wird, Caches und Browserdaten löschen, danach nochmal probieren.

**Comment by FabianWilms** [comment]
https://github.com/xdoo/lhm_animad_admin_html5/issues/28#issuecomment-353260622 nehme ich zurück. Auch hier waren noch gecachete Datenreste vorhanden. Bei "leerem" Browser funktioniert die Anwendung unter `build/es5-bundled` auch so nicht.

**Comment by FabianWilms** [comment]
Bis (einschließlich) commit b472497164fef10f6ceceafaa349c6b1365b31ef hat der build noch funktioniert. Mit den beiden Änderunge 535715bc20f3ac21a5f0adc1232d9bdcd75adfa8 und 38954f939fd97a2874823db36c82af55c573b1b0 funktioniert er nicht mehr

**Comment by xdoo** [comment]
@FabianWilms  in der index.html steht webcomponents-lite statt webcomponents-loader. Damit laden wir immer den gleichen Satz an Polyfills statt das Browser abhängig zu machen. Ist das Absicht, oder ist diese Zeile übrig geblieben?

`    
    <script src="/bower_components/webcomponentsjs/webcomponents-lite.js"></script>`

**Comment by FabianWilms** [comment]
Ich glaube, dass kannst du sogar wieder rausnehmen. @peter-mueller und ich haben festgestellt, dass das automatisch nach dem polymer build in  der index.html steht. 

Siehe hier:

Vorher: https://github.com/peter-mueller/knocklock/blob/master/index.html#L15

Nach dem build: https://github.com/peter-mueller/knocklock/blob/gh-pages/index.html#L9

**Comment by xdoo** [comment]
Änderungen wieder rückgängig machen. Siehe oben.

**Comment by xdoo** [comment]
Im Firefox (57.0.4) tritt der Fehler bei mir nach wie vor auf:
`Mit document.write() wurde ein nicht balancierter Baum geschrieben, was dazu geführt hat, dass Daten aus dem Netzwerk neu geparst werden mussten. Für weitere Informationen https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing
lhm_animad_admin_html5:6
TypeError: script is null
[Weitere Informationen]
lhm_animad_admin_html5:66:9
TypeError: Polymer is not a function
[Weitere Informationen]
lhm_animad_admin_html5:99:1
TypeError: Polymer is not a function
[Weitere Informationen]
lhm_animad_admin_html5:112:1
TypeError: Polymer is not a function
[Weitere Informationen]
lhm_animad_admin_html5:113:1
TypeError: Polymer is not a function
[Weitere Informationen]
lhm_animad_admin_html5:113:447
TypeError: Polymer is not a function
[Weitere Informationen]
lhm_animad_admin_html5:113:14
TypeError: Polymer is not a function
[Weitere Informationen]
lhm_animad_admin_html5:113:26
TypeError: Polymer is not a function
[Weitere Informationen]
lhm_animad_admin_html5:113:1
TypeError: Super expression must either be null or a function, not undefined
lhm_animad_admin_html5:3:1618
Registrieren eines ServiceWorker ist fehlgeschlagen: Der Pfad des angegebenen Gültigkeitsbereichs 'https://xdoo.github.io/' ist nicht unterhalb des maximal erlaubten Gültigkeitsbereichs 'https://xdoo.github.io/lhm_animad_admin_html5/'. Passen Sie den Gültigkeitsbereich an, verschieben Sie das ServiceWorker-Skript, oder verwenden Sie die HTTP-Kopfzeile Service-Worker-Allowed um den Gültigkeitsbereich zu erlauben.
lhm_animad_admin_html5`

**Comment by xdoo** [comment]
#51 könnte das selbe Problem haben.

**Comment by rowe42** [comment]
@FabianWilms @peter-mueller @xdoo Könntet ihr es nochmal ausprobieren? Mir ist nicht ganz klar, um welchen Fehler es eigentlich geht, welche Auswirkungen dieser hat und ob er überhaupt noch existiert. Würde gerne das Issue konkretisieren oder ggf. als gelöst schließen.

**Comment by FabianWilms** [comment]
Wenn du auf https://xdoo.github.io/lhm_animad_admin_html5/ gehst, siehst du in der Konsole verschiednste Fehlermeldungen. Auch wird die Seite selbst nicht angezeigt. Dies entsteht dadurch, dass die Anwendung unter einem Sub-Path (`lhm_animad_admin_html5`) gehostet wird, und deswegen die relativen Pfade teilweise nicht mehr stimmen.

Gerade wenn später evtl. verschiedene Oberflächen über ein API-Gateway gehostet werden sollen, wird dieses Problem (aufgrund der verschiedenen Root-Paths) wieder auftauchen.

Mittlerweile habe ich aber eine Lösung gefunden, diese ist in folgendem commit zu sehen: https://github.com/FabianWilms/anwesenheit/commit/2fda9ccc170d3eb432f58f9e9a72e1f0a65cffc2

Es muss, wenn die Anwendung nicht unter "/" gehostet wird, der `basePath` angegeben werden. Dadurch wird auch das Polymer-Property `rootPath` gesetzt, welches auch beim Routing verwendet werden sollte (siehe als Beispiel der korrekten Verwendung das Polymer Starter Kit: https://github.com/Polymer/polymer-starter-kit/blob/master/src/my-app.html#L88).

**Comment by rowe42** [comment]
@FabianWilms Verstehe ich das richtig:
- in der aktuellen Version (die unter / läuft) haben wir keine Probleme (mehr), wenn wir das im OpenShift laufen lassen (und nicht bei Github-Pages)
- wenn wir in `polymer.json` noch `"basePath": "/"` angeben, kann man das später leichter erweitern, wenn man wirklich mal mehrere Anwendungen in einem API-Gateway haben will (derzeit ist ja der Plan, pro Anwendung einen eigenen API-Gateway zu generieren)

Dann ergänze ich die Zeile in polymer.json noch und schließe das Issue, ok?

**Comment by FabianWilms** [comment]
Wenn das der Plan ist, ist das eine Lösung 😜 Man sollte es nur im
Hinterkopf behalten.

rowe42 <notifications@github.com> schrieb am Mi., 28. März 2018, 08:05:

**Comment by rowe42** [comment]
Eingecheckt in Barrakuda-Branch _#296

**Comment by rowe42** [comment]
Jetzt im Barrakuda-Polymer-Master-Branch "polymer-ui2"

**Comment by rowe42** [comment]
Da es die Anbindung zumindest nicht "bricht", schließe ich das Issue.
