### ISSUE TITLE
Überflüssiges Event detail aus Polymer-Doku

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/lhm_animad_admin_html5#283]
Hallo,

bei: 
https://github.com/xdoo/lhm_animad_admin_html5/blob/402a448ccfa3a47110b1d316bd838c32e4d36ed3/src/behaviors/animad-form-behavior.html#L179

[Suche für weitere Stellen](https://github.com/xdoo/lhm_animad_admin_html5/search?utf8=%E2%9C%93&q=%22{kicked%3A+true}%22&type=)

Wird die `kicked: true` Information wo benötigt?

## Expected Behavior

Nur das Event für den reload wird versendet.

## Actual Behavior

Das Event wird mit wahrscheinlich nicht benutzten Zusatzdaten versendet. Das `detail: {kicked: true}` wurde wahrscheinlich einfach aus der [Polymer Doku](https://www.polymer-project.org/2.0/docs/devguide/events#custom-events) mit kopiert. 

## Lösung: 
Löschen :smile:

**Comment by rowe42** [comment]
@peter-mueller 
Richtig. Kann man löschen. ABER: Wir machen ab sofort keine direkten Änderungen mehr im Zoo-Beispiel, ohne das auch im Generator anzupassen. Darum bitte stattdessen ein Issue im Gitlab aufmachen, gern auch selber fixen (im Branch `polymer-ui2`) und per MR an Boxi.

Ist übrigens im Security-Bereich auch so gemacht. Vielleicht magst du das im gleichen Zug auch gleich mitfixen (und natürlich testen, dass es danach noch wie vorher funktioniert).

Dieses Issue dann bitte wieder zumachen (gern mit Verweis auf das Gitlab-Issue).

Danke!

**Comment by xdoo** [comment]
This issue was moved to xdoo/move_issues#1
