### ISSUE TITLE
User Information separieren

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#33]
Die Information der Nutzer über Toasts sollte in ein eigenes Mixin ausgelagert werden, dass bei Bedarf verwendet werden kann. Grund ist, dass man potenziell an unterschiedlichen Stellen auf die Toasts zurückgreifen will. In der Regel immer dann, wenn man eine Kommunikation mit dem Backend hat und diese nicht funktioniert. Da muss man zwar auch auf die Konsole loggen, aber den Nutzer sollte man ebenfalls über das Problem informieren.

**Comment by xdoo** [comment]
@peter-mueller dieses Ticket hatte ich gestern gemeint. Die Idee das über Events zu lösen finde ich ganz charmant.

**Comment by ejcsid** [comment]
@xdoo Kann das auf Milestone 3.0 geschoben werden? Wenn nicht: Bitte genauer beschrieben, was zu tun ist.

**Comment by rowe42** [comment]
@ejcsid ich nehme an das ist genau das, was du gestern implementiert hast. Können wir das issue schließen?

**Comment by ejcsid** [comment]
Ich habe nur die Methode zur Anzeige der Fehlermeldung in ein behavior umgezogen. @rowe42: Die anderen Anzeigen sind noch in animad-app. Ich würde sagen: das ist noch nicht vollständig implementiert. Das behavior sollte dann wahrscheinlich auch umbenannt werden.

**Comment by rowe42** [comment]
Die Toasts selbst lassen sich ja nicht umziehen. Außerdem sind die in animad-app schon ziemlich zentral platziert. Bei einem anderen Platz gäbe es auch wieder Probleme mit der Sichtbarkeit.
Mir persönlich würde das was du gemacht hast reichen um das issue zu schließen. Aber wir können gern noch abwarten was @xdoo als Autor des Issue sagt.

**Comment by xdoo** [comment]
Der schließt sich eurer Meinung an :)

**Comment by rowe42** [comment]
Schließe das Issue nach Kommentar von @xdoo .
