### ISSUE TITLE
HAL Format bei Requests 

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#36]
Aktuell ist die Oberfläche noch nicht in der Lage mit dem generierten Backend zu kommunizieren. Hierzu muss die Oberfläche in die Lage versetzt werden, das HAL Format zu verstehen.

**Comment by xdoo** [comment]
Zur Konkretisierung: In diesem Ticket geht es ausschließlich darum, die Payload aus dem HAL Format auszulesen. Mitgelieferte Links werden ignoriert.

**Comment by xdoo** [comment]
Siehe auch #48 bezüglich der HATEOAS Links.
Siehe auch #9.

**Comment by xdoo** [comment]
Hier die entsprechende Payload bei lesendem Zugriff:
```
{
  "_embedded": {
    "enclosures": [
      {
        "name": "Elephant's Paradise",
        "cleaningTime": "15:15:15",
        "_links": {
          "self": {
            "href": "http://localhost:39146/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5"
          },
          "enclosure_": {
            "href": "http://localhost:39146/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5"
          },
          "animalList": {
            "href": "http://localhost:39146/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5/animalList"
          }
        }
      }
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost:39146/enclosures"
    },
    "profile": {
      "href": "http://localhost:39146/profile/enclosures"
    },
    "search": {
      "href": "http://localhost:39146/enclosures/search"
    }
  }
}
```

**Comment by xdoo** [comment]
@ejcsid du lädst die Daten ja bereits vom Server. Verwendest du hier auch das HAL Format?

**Comment by ejcsid** [comment]
@xdoo Das Backend liefert die Daten im HAL Format. Die ID kommt aus _embedded.keepers._links.self.href. Die Anzeige für das skill[] ist noch nicht lokalisiert.

**Comment by xdoo** [comment]
Wir müssen überlegen, wie wir hier die Komponenten übergreifende Kommunikation hin bekommen. Ich habe jetzt die Formulare HAL / HATEOAS fähig gemacht. Den Merge Request schicke ich dir heute noch, dann können wir morgen mal drüber sprechen wie wir das machen wollen.
