### ISSUE TITLE
Menübutton fixen

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#40]
Aktuell hat der Menübutton links oben keine Funktion.

**Comment by rowe42** [comment]
Habe es gemacht wie hier: https://raw-dot-custom-elements.appspot.com/PolymerElements/app-layout/v2.0.4/app-layout/demo/demo6.html
Code im Github hier: https://github.com/PolymerElements/app-layout/blob/master/demo/demo6.html
(allerdings etwas umgebaut)
