### ISSUE TITLE
Startbildschirm grau - service-worker.js fehlt

### ISSUE THREAD

**Issue by dragonfly28** [xdoo/lhm_animad_admin_html5#51]
Beim Deployment auf Github Pages ist nur eine graue Seite zu sehen
-> https://dragonfly28.github.io/lhm_animad_admin_html5/

Folgende Meldung erscheint in der JS Webkonsole:
Registrieren/aktualisieren eines ServiceWorker für Gültigkeitsbereich 'https://dragonfly28.github.io/' ist fehlgeschlagen: Laden des Skriptes 'https://dragonfly28.github.io/service-worker.js' mit Status 404 fehlgeschlagen.
TypeError: ServiceWorker script at https://dragonfly28.github.io/service-worker.js for scope https://dragonfly28.github.io/ encountered an error during installation.

**Comment by xdoo** [comment]
Kann das Issue auf einem lokalen Server nicht nachstellen. Ob die Anwendung auf github pages läuft hat m.M. nach keine Relevanz. Wenn ich folgende Schritte durchführe:
```bash
polymer build
cd build/es5-bundled/
python -m SimpleHTTPServer
```
kann ich die Anwendung ganz normal aufrufen und benutzen. Bitte Issue schließen.

**Comment by rowe42** [comment]
Annahme, dass das lokal bzw. in OpenShift kein Problem darstellt. Wird geschlossen.
