### ISSUE TITLE
Aufteilung auf Cards oder mittels Divider?

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#52]
Problem: Bei Objekten mit vielen Feldern wird eine Seite schnell lang und unübersichtlich. Eine optische Trennung von Absätzen würde die Lesbarkeit / Bedienbarkeit erhöhen.

Dabei gibt es die Optionen:
1. Cards (Beispiel: https://expandjs.com/components/mat-toast)
2. Dividers
![dividers](https://user-images.githubusercontent.com/25983841/34877598-915ddb42-f79e-11e7-9fff-b2f0feccd424.png)
3. Andere?

Fragen:
- Benötigen wir eine optische Trennung von Absätzen? Welche der o.g. Optionen sollen zum Einsatz kommen?
- Soll dies bereits mit generiert werden? Müssen wir dazu die DSL erweitern oder lässt sich das mittels der bestehenden DSL modellieren (Idee von Claus im AG-Meeting: Jeder zu separierende Abschnitt als eigenes "component" modellieren und damit auch eine eigene "form" modellieren).

**Comment by xdoo** [comment]
Ich schlage hier tatsächlich vor, dass jeder Abschnitt als eigene Entität modelliert wird. Diese Entitäten werden von der Entität "Fall" referenziert. Der Generator würde mir für all diese Entitäten Komponenten erzeugen. Beispielsweise entsprechende Formular Komponenten. Diese Komponenten kann man nehmen und einen beliebigen "Container" einbetten. D.h. auch meiner Sicht stellt sich die Frage nach Cards, Divider, etc. in unserem Kontext gar nicht. Das ist eine Entscheidung in dem jeweiligen Projekt. Was ich wichtig finde: Das Projekt sollte diese Freiheit haben, ohne auf die Vorteile des Generators verzichten zu müssen. Genau das ist die Idee hinter der Komponenten basierten GUI.

Ich nehme mal die Kollegen mit in die Diskussion: @dragonfly28 @ejcsid

**Comment by rowe42** [comment]
Hier mein Verständnis:
Ein DSL-Schnipsel, der so aussieht:

```
    view animals appearsInMenu {
        component animals for administration.animal type Table {
            button detail navigatesTo animalDetailView;
        }
        component createAnimal for administration.animal type CreateForm {
            button save navigatesTo animals;
        }
        button CreateAppointment navigatesTo appointmentView;
    }
```
wird zu einer generierten View, die derzeit im Generator so aussieht:
![vaadin-animals](https://user-images.githubusercontent.com/25983841/34884108-96a1fa92-f7b3-11e7-8110-bddab5875b85.png)

In dem heutigen Generat gibt es also keine optischen Trenner o.ä. zwischen den beiden Komponenten "animals" und "createAnimal". 
Also: Selbst wenn wir es so machen, dass wir die Unterabschnitte von Fall als eigene Entitäten modellieren (was wir noch aus anderen Gesichtspunkten diskutieren sollten), stellt sich doch die Frage, was der zukünftige Generator standardmäßig zwischen die Komponenten packt.

Hier gibt es die Optionen:
a) gar nichts (wie oben)
b) jede Komponente kommt auf eine eigene "Card"
c) ein Divider

D.h. aus meiner Sicht stellt sich die Frage nach Cards, Divider etc. doch!
Oder habe ich da einen Denkfehler irgendwo?

**Comment by rowe42** [comment]
OK, das mit der Erwartungshaltung an die Views müssen wir dann nochmal generell diskutieren (in einem anderen Issue?). Ich verstehe ja, dass man die Views noch am ehesten an die Erwartungen der Nutzer anpassen muss. Aber warum sollte man denn nicht die Views initial schon so machen, dass sich nicht in 10% der Fälle sondern in 50% der Fälle ohne weitere Anpassung passen?
Und irgendwas muss ja zwischen den Komponenten sein (wenn wir das entscheiden, auch "nichts"), d.h. das sollte man bewusst entscheiden.
Außerdem: Es mag ja sein, dass ein Divider einfach zu ergänzen ist. Aber jede Komponente auf eine einzelne Card zu packen, ist dagegen ggf. nicht mehr ganz so trivial.

**Comment by xdoo** [comment]
Es gibt gleich mehrere Gründe warum man hier nicht zu viel machen will:

- Alles was generiert wird, muss in Generator umgesetzt werden.
- Viele Dinge sind in Code einfacher zu lösen.
- Die DSL wird überfrachtet und ist nicht mehr einfach zu bedienen.
- Die Views sind das, was eh am meisten angefasst wird.
- Wenn man den Generator beherrscht, dann ergeben sich bestimmte Probleme gar nicht (siehe Code Beispiel oben).

**Comment by dragonfly28** [comment]
KISS!!!
Aus einer Entität werden einheitlich immer mehrere Komponenten generiert (z.B. AnimalListView, AnimalDetailView, AnimalCreateView, ...), die von Entwicklern ausgewählt und miteinander verbunden werden können.
Modellierbare, graphische Unterteilungen innerhalb dieser Views halte ich für unnötig, da dies eher für schlechte Modellierung spricht als für fehlende Funktionalität in der UI. Könnte man bestenfalls als Enhancement für später einstellen.

**Comment by rowe42** [comment]
1. Wenn ein Entity sehr viele Felder beinhaltet, werde ich das irgendwie graphisch unterteilen bzw. anordnen wollen. Aus diesem Grund dann im Datenmodell verschiedene Entities zu erzeugen, kommt mir nicht der richtige Ansatz vor. Es könnte sich aber natürlich ein Ansatz finden, dies nachträglich z.B. über CSS Mixins zu realisieren, ohne dabei die Komponente selbst verändern zu müssen.
2. Im Issue oben habe ich auch explizit gefragt, wie wir es gestalten wollen, wenn mehrere Komponenten auf einer Seite dargestellt werden. Z.B. als jeweils separate Card oder alles auf einer Card aber mit Devidern getrennt.

**Comment by xdoo** [comment]
Zu 2.: das ist eine Entscheidung des Projektes. Jeder sollte das machen, wie er es für richtig hält. Aus meiner Sicht ist das fachlich und kann nicht generisch gelöst werden.. 

Btw. wir sollten unterschiedliche Aspekte in unterschiedlichen Issues diskutieren. Die Frage nach dem View Design (mehrere Objekte auf einer View) ist etwas anderes, als die Frage wie wir mit großen Objekten umgehen.

**Comment by rowe42** [comment]
Ich habe jetzt die Views so angepasst:
- Zwischen den Komponenten kommt eine horizontale Linie (<hr> mit Styling)
- Jede Komponente bekommt eine Überschrift (<h2>)
- Jede View bekommt ihrerseits auch eine Überschrift (<h1>)

Das generieren wir dann auch so. Wenn ein Projekt das dann nicht haben will, macht es das eben weg / anders.

Eingecheckt in Branch _#244.

**Comment by rowe42** [comment]
Wie oben beschrieben jetzt in master. Schließe da Issue.
