### ISSUE TITLE
Einsatz von Collapse-Buttons

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#53]
**Problem:** Bei Objekten mit vielen Feldern wird eine Seite schnell lang und unübersichtlich. 
Eine Möglichkeit wäre es, einzelne Abschnitte mit "Collapse-Buttons" zu versehen, damit sie der User zur besseren Übersicht einklappen kann (siehe z.B. https://www.webcomponents.org/element/Collaborne/paper-collapse-item oder https://www.webcomponents.org/element/jifalops/iron-collapse-button).

Beispiel:
![collapse-offen](https://user-images.githubusercontent.com/25983841/34878303-9d601df8-f7a1-11e7-952e-a46c635b2bb8.png)
![collapse-zu](https://user-images.githubusercontent.com/25983841/34878307-9f01605e-f7a1-11e7-84ce-a6db5045e59f.png)

Fragen:
- Sollen Collapse-Buttons zum Einsatz kommen?
- Soll der Generator einen Collapse-Button standardmäßig mit generieren? Oder soll ein Collapse-Button via DSL konfigurierbar sein (dazu müsste die DSL angepasst werden)? Wenn ja, soll der Bereich standardmäßig auf- oder zugeklappt sein?
- Was soll im zugeklappten Modus standardmäßig zu sehen sein? z.B. immer die Überschrift des Bereichs?

**Comment by xdoo** [comment]
Wo siehst du hier die Unterscheide zur Diskussion von #52 ? Aus meiner Sicht ist das genau das gleiche Problem.
