### ISSUE TITLE
Seitennavigation im rechten Menü bei langen Seiten

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#54]
**Problem:** Bei Objekten mit vielen Feldern wird eine Seite schnell lang und unübersichtlich.
Man könnte ein Menü rechts einblenden, in dem die Struktur der Seite anhand der Überschriften der Abschnitte abgebildet ist und man beim Klick zur entsprechenden Stelle springt.

Fragen:
- Wollen wir so eine Art Seitennavigation einführen? Wollen wir dafür ein Menü rechts verwenden?
- Wie soll sich das Menü im mobilen Fall verhalten? Ausgeblendet werden?
- Soll die Seitennavigation mit generiert werden? Wenn ja, für alle Seiten oder nur für lange Seiten? Wenn ja, wie ist "lang" definiert?

**Comment by xdoo** [comment]
Auch hier denke ich, dass es genau die selbe Diskussion wie unter #52 ist.

**Comment by rowe42** [comment]
Es geht um das gleiche Grundproblem, aber unterschiedliche Ideen (Cards/Dividers vs. rechtes-Menü). Man kann diese Ideen unabhängig voneinander einführen (z.B. rechtes-Menü machen, aber keine Dividers). Deshalb habe ich hieraus ein separates Issue gemacht.

**Comment by Baumfrosch** [comment]
Ich würde auch lieber erstmal prüfen, ob das Datenmodell richtig ist. Wenn eine Klasse sehr viele Attribute hat, sollte man prüfen, ob sie sich nicht besser zerlegen lässt.
Ich schlage vor, wir schauen uns erstmal kritisch das Bezweck-Datenmodell an, bevor wir aufwändige Lösungen kreieren.

**Comment by dragonfly28** [comment]
see #52

**Comment by rowe42** [comment]
@olympialice Bitte im Wiki-Artikel bearbeiten und dann hier schließen.

**Comment by olympialice** [comment]
Im Wiki als ToDo "Bezweck" beobachten aufgenommen ;-)
