### ISSUE TITLE
Menüs

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#58]
Im unserem Zoo-Beispiel und auch im Generator wird bislang ausschließlich das linke Menü verwendet. Man könnte aber auch das Top-Level-Menü, das rechte, das untere Menü oder den FAB verwenden: https://material.io/guidelines/layout/structure.html#structure-ui-regions  (siehe Desktop)

![desktop-structure](https://user-images.githubusercontent.com/25983841/34879520-75e2f7b0-f7a5-11e7-81c1-5b3dc73772ba.png)

**Fragen:**
- Wollen wir weitere Menüs einsetzen? Wenn ja, welche und fachlich für welchen Zweck? Vgl. auch Issue #54 
- Je nach Entscheidung: Soll das auch im Generator berücksichtigt werden?

**Comment by xdoo** [comment]
Das ist aus meiner Sicht eine individuelle Entscheidung des Projektes.

**Comment by xdoo** [comment]
Ich nehme mal die Kollegen mit in die Diskussion: @dragonfly28 @ejcsid

**Comment by Baumfrosch** [comment]
Das Ganze ist für mich ja eine Gratwanderung zwischen "einheitliches Look&Feel" und "Freiheiten fürs Projekt".
Ich finde es ist ein Mehrwert, wenn die Menüs unserer Anwendungen einheitlich sind. Wenn man es einfach dem Projekt überlässt ist die Gefahr groß, dass die Anwender die Oberfläche so wünschen, wie sie es von ihrer Alt-Anwendung oder aus ihrem persönlichen Umfeld kennen.
Im ersten Schritt plädiere ich dafür, das Menü so wie bisher links zu lassen. Wenn man andere Menüs einsetzt, braucht man zumindest ein paar Guidelines. Das können wir dann diskutieren, wenn der erste Fall kommt.

**Comment by xdoo** [comment]
Die Guidlines sind m. M. durch Material Design bereits da.

**Comment by Baumfrosch** [comment]
Ich habe eine Zeit recherchiert, vielleicht aber nicht die richtige Stelle gefunden. Hast du einen Link für mich, @xdoo ?

**Comment by xdoo** [comment]
Nur den, der oben schon drin steht. Damit ist aus meiner Sicht das "Look & Feel" klar. Was fachlich dargestellt wird, muss das Projekt entscheiden (außer bei der Linken Navigation - die wird tatsächlich vorgegeben).

Das sollte uns nicht daran hindern, dass wir Vorschläge machen, für was sich die einzelnen Regionen besonders gut eignen. Beispielsweise die rechte Navigation für administrative Aktionen. Oder die App Bar um die Nutzereingaben zu steuern.

**Comment by rowe42** [comment]
@olympialice Bitte auch im Wiki bearbeiten und dann hier schließen.

**Comment by olympialice** [comment]
Ich habe die weiteren Layout-Möglichkeiten nach Material Design in das Wiki aufgenommen und mir dort ein ToDo eingetragen, mit Euch zu besprechen, welche Vorschläge für eine Nutzung der einzelnen Navigationsbereiche man machen könnte.
