### ISSUE TITLE
WebAnimations Polyfill

### ISSUE THREAD

**Issue by FabianWilms** [xdoo/lhm_animad_admin_html5#6]
In älteren Browsern kommt folgende Fehlermeldung, beim öffnen eines Dropdowns:

`No web animations detected. This element will not function without a web animations polyfill.`

Siehe dazu https://github.com/PolymerElements/paper-dropdown-menu/blob/2.0-preview/README.md#changes-in-20

**Comment by xdoo** [comment]
`
  <link rel="import" href="../../neon-animation/web-animations.html">`
