### ISSUE TITLE
Objektsuche in Tabellen

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#60]
Wir brauchen die Möglichkeit, in einer großen Anzahl von Objekten zu suchen – entweder in einem Google-artigen Freitextfeld oder typisiert (siehe ForeUI-Mockup → Fallanlage). 

![suche-foreui](https://user-images.githubusercontent.com/25983841/34879641-ce5453da-f7a5-11e7-9184-4e50a8b710c3.png)

Unsere Tabelle hat schon ein Suchfeld. In welchen Feldern sucht dieses? Wie kann man hier steuern, z.B. wenn man nur in einer Spalte suchen will? 

Vielleicht könnte man ein Search-by-Example in die Spaltenüberschrift einbauen (kann vaadin-grid, siehe https://www.webcomponents.org/element/vaadin/vaadin-grid/demo/demo/index.html, Sorting-and-Filtering)?

![search-by-example](https://user-images.githubusercontent.com/25983841/34879721-144592be-f7a6-11e7-9707-a0fc6d0e4006.png)

Dieses sollte sich aber - anders als im Beispiel - immer noch kombinieren lassen mit Sortierung der Spalten, so dass man auch ein gefiltertes Ergebnis noch sortieren kann.

@ejcsid

**Comment by rowe42** [comment]
Nachtrag: Wir müssen auch Anforderungen wie "von-bis" oder "größer-als" abbilden können. Mit den aktuell einblendbaren Filtern geht das nur bedingt, da man dort ja die Wahlmöglichkeiten explizit vorgeben muss.
Besser wäre es, dies über eine Semantik in die oben gezeigten Search-by-Example-Felder einbauen könnte, z.B. ">15".

**Comment by xdoo** [comment]
In diesem Ticket werden m. M. nach zwei völlig unterschiedliche Sachen in einen Topf geworfen:

Suche != Filtering

Eine Suche findet über den Server statt und lädt eine Auswahl von Daten in die GUI (das ist aktuell in der Vaadin GWT Version implementiert). Ein Filtering findet auf der Datenbasis, die sich bereits in der GUI befindet. Ich würde empfehlen diese beiden Aspekte getrennt voneinander zu betrachten.

**Comment by xdoo** [comment]
Ich nehme mal die Kollegen mit in die Diskussion: @dragonfly28 @ejcsid

**Comment by ejcsid** [comment]
Zu der Frage: 'In welchen Feldern sucht dieses?' Es werden alle Datensätze weggefiltert, die nicht wenigstens in einem der Felder den eingegebenen Text (case-insensitive) enthalten. z.B.: Nach Eingabe: 'am' zeigt die Keepers-Liste alle Datensätze an, die im Vornamen, Nachnamen oder in Erfahrung ein 'am' haben. Es wird keine Suche im Backend aufgerufen.

Ich sehe im Moment noch keinen Mehrwert, nur nach einer Spalte zu filtern. Hast du ein Beispiel?

Das vaadin-grid-Beispiel schau ich mir an.

**Comment by rowe42** [comment]
Wenn ich jetzt mal fachlich denke: Warum sollte ein Filtering sich nur auf die lokale Datenbasis beziehen? Das würde mir als User nicht einleuchten, da es mir als User egal ist, wieviel der zentralen Datenbasis bei mir lokal im Speicher gehalten wird.
Im Gegenteil: Wenn es technisch so ist, dass sich der Filter nur auf den lokalen Datenbestand anwenden lässt, sollten wir das nicht verwenden, da es den User nur verwirrt. Dann brauchen wir aber im Gegenzug eine selbstgebaute search-by-example.

**Comment by xdoo** [comment]
Wir haben im Backend eine Fuzzy Search auf Basis von Lucene. Dort kann man zu jeder Entity die Mainfeatures durchsuchen. 

Der Unterschied aus Sicht des Nutzers ist relativ leicht und meiner Meinung nach nicht verwirrend:

- Eine Suche bringt erst ein Ergebnis, wenn ich gesucht habe. So wie Google erst dann eine Ergebnisliste zeigt, wenn ich gesucht habe.  
- Beim Filterin ist die Tabelle bereits gut gefüllt und ich will die angezeigten Werte auf genau die reduzieren, die mich im Moment interessieren.

Aus meiner Sicht sind das zwei valide Anwendungsfälle, die allerdings wenig miteinander zu tun haben.

**Comment by Baumfrosch** [comment]
Suchen und Filtern muss man unterscheiden. Fachlich gehört es aber zusammen. Die Anforderung ist ja aus einer Menge von Objekten das richtige oder die richtigen zu finden. Sobald die Menge größer wird, kommt oft die Anforderung nach mehreren Kriterien einzuschränken, z.B. um sich einen Überblick über seine Arbeit zu verschaffen. In unseren Beispiel könnten alle offenen oder in Arbeit befindlichen Fälle, die meinem Team zugeordnet sind, gesucht werden. Alle Attribute - wie im Beispiel oben - auf ein Form zu schreiben wird unübersichtlich und lässt auch keine Oder-Verknüpfung zu oder eine Verneinung.
Ich denke wir sollten bei einem Suchfeld bleiben und Suchoperatoren erlauben.
Mein Beispiel könnte dann so aussehen: "Team:XYZ (Fallstatus:offen OR Fallstatus:In Arbeit)".
Ist so etwas umsetzbar?

**Comment by rowe42** [comment]
Meiner Meinung nach sollte es so funktionieren:
1. Ich rufe die Seite der Fälle auf, die eine Tabellenübersicht enthält. Es werden automatisch in einem Paging die ersten 20 offenen Fälle angezeigt. Über das Paging kann ich aber auch seitenweise durch die Fälle navigieren.
2a. Ich kann nun im allgemeinen Suchfeld direkt über der Tabelle einen Begriff eintippen, der in allen Spalten gesucht wird. Es werden nur noch die Fälle mit dem gesuchten Term angezeigt.
2b. Ich kann aber auch alternativ oder zusätzlich in das Feld über der jeweiligen Spalte klicken und dort einen Term eintippen. Die Fälle werden weiter gefiltert, es werden nur noch die angezeigt, die auch in dieser Spalte den eingegebenen Term enthalten.

So kann ich entscheiden, ob ich google-like in allen Feldern suchen will oder spezifisch in einem bestimmten Feld. Und ich kann per search-by-example verschiedene Felder kombinieren. Nachteil wäre, dass eine Oder-Verknüpfung der Felder nicht möglich wäre.

Erstmal eine leere Tabelle zeigen und darauf zu warten, dass der User etwas sucht - wie bei Google - finde ich beim Suchfeld, das direkt zu einer Tabelle gehört, nicht so sinnvoll.

Man kann von mir aus noch ein generelles Suchfeld (z.B. im Menü oben) haben, in dem man dann tatsächlich fuzzy in allen Objekten (Fälle, Aktivitäten usw.) gleichzeitig suchen kann. 

Die Suche in einzelnen Feldern NUR über Suchterms der Form 
"Team:XYZ (Fallstatus:offen OR Fallstatus:In Arbeit)" zu ermöglichen, finde ich nicht Anwender-freundlich. Nicht jeder User möchte so eine Syntax auswendig lernen. Das sollte man wenn dann nur als optionale zusätzliche Möglichkeit bieten.

Ich halte das für ein sehr wichtiges Thema und würde gerne auch Input aus dem SOZ zu diesem Thema haben.

@Baumfrosch : Mein Vorschlag war auch nicht, den Screenshot oben aus dem ForeUI-Prototypen zu realisieren, sondern per Suchfeldern direkt über den Spalten der Tabelle (zweiter Screenshot oben).

**Comment by xdoo** [comment]
Ich würde vorschlagen sich mal von dem bezweck Fall zu lösen. Suche und Filtern sind auch fachlich nicht das selbe. Es gibt auf der Welt nicht nur Fälle. Ein sehr häufiger Anwendungsfall ist beispielsweise die SUCHE nach Personen. Niemand würde erwarten,  dass eine Ergebnistabelle gefüllt ist, bevor ich dort den Namen eingeben habe. 

Auf der anderen Seite habe ich beispielsweise 30 Aktionen, die ich einfach FILTERN will um an die relevanten zu kommen, ohne die Liste durchsehen zu müssen.

Es bringt nichts dieser beiden Fälle gemeinsam lösen zu wollen. Sie sind fachlich und technisch fundamental unterschiedlich.

**Comment by Baumfrosch** [comment]
Um konstruktiv mitdiskutieren zu können bräuchte ich mal eine klare Definition von Filtern und Suchen. Kann mir außerdem jemand sagen, was wir wie in der Referenzarchitektur implementiert haben bzw. wo ich das nachlesen kann.

Vom Bezweckfall lösen finde ich nicht gut. Erstens müssen wir hier sinnvolle Lösungen finden und zweitens habe ich ja versucht, die generische Anforderung zu formulieren, drittens gibt es auf der Welt nicht nur Fälle, aber bei uns bzw. im ÖD ist der  Fall ein ziemlich zentrales Objekt.

Ich versuche nochmal die generische Anforderung zu formulieren:
Ich will aus einer Menge von Objekten eine bestimmte, definierte Untermenge. Aus der Trefferliste will ich ein Objekt zur Bearbeitung auswählen.

Beispiele:
Alle offenen Rechnungen, deren Rechnungsbetrag über 1000,- € ist und die in den nächsten zwei Wochen fällig werden.

Alle Vorhaben, für die ich zuständiger PM bin und die im nächsten Quartal starten.

**Comment by xdoo** [comment]
Let me google that for you ;) 

https://ux.stackexchange.com/questions/4752/search-vs-filter-what-is-the-difference

Suche: Ich habe noch kein Ergebnis und hole mir die Daten über Parameter vom Server.
Filtern: Ich habe bereits eine Datenmenge, aus der ich die passenden heraus suche.

Suche mache ich bei einer großen bis mittleren Datenbasis, Filtern bei einer kleinen.

Umgesetzt auf deine Anforderung:

> Ich will aus einer Menge von Objekten eine bestimmte, definierte Untermenge. Aus der Trefferliste will ich ein Objekt zur Bearbeitung auswählen.

Der erste Satz ist für mich die Suche, der zweite Satz Filtern.

**Comment by xdoo** [comment]
Anyway - ich bleibe dabei:

> Es bringt nichts diese beiden Fälle gemeinsam lösen zu wollen. Sie sind fachlich und technisch fundamental unterschiedlich.

Ich würde dieses Issue zu machen und jeweils eines für Filter und eines für Suche aufmachen.

**Comment by rowe42** [comment]
Ich sehe es anders: Der Nutzer möchte mit möglichst wenigen Schritten an das gesuchte Objekt kommen. Genau darum geht es in diesem Issue. Ob der Nutzer sucht oder filtert ist ihm dabei egal.

Meiner Meinung nach ist die Anforderung:
- Ich möchte in einer Liste Objekte (z.B. die Fälle) einen bestimmten finden, z.B. den für den Nachnamen "Werner" (und es ist wichtig, dass es um den Nachnamen geht; ich will nicht die Fälle finden mit dem Vornamen "Werner" oder einer Straße mit Teilstring "Werner")
- Ich möchte mir NICHT eine kryptische Syntax merken müssen (z.B. "nachname contains werner"), die ich dann ein ein einzelnes Suchfeld eintippen muss, sondern ich will hier in der Oberfläche möglichst gut geführt werden
- Ich möchte das Gesuchte in möglichst wenigen Schritten erreichen

Wenn wir nun Suchen (über Suchfeld) und Filtern (über Filter oberhalb der einzelnen Spalten) trennen, bleibt mir nur folgende Vorgehensweise:
- Start mit leerer Tabelle
- Eingabe von "*" oder "Werner" in Suchfeld und klick auf Suchen --> ich bekomme alle Fälle bzw. alle Fälle, in denen "Werner" irgendwo vorkommt
- Erneute Eingabe von "Werner", diesmal über der Spalte Nachname --> nun endlich bekomme ich, was ich will

Ich finde, wir sollten das direkter zugänglich machen, und zwar so, wie ich es weiter oben schon beschrieben habe. Das würde aber bedeuten, dass die Felder über der jeweiligen Spalte auch Suchfelder sind, die direkt auf dem Datenbestand auf dem Server suchen. Ein Filtern im lokalen Datenbestand würde es in der Art nicht geben und auch nicht brauchen.

**Comment by Baumfrosch** [comment]
Das ist auch mein Verständnis von Suchen und Filtern.
Dann trennst du die Themen, @xdoo  ?
Mein Punkt ist dann: wie implementiere ich ein Suchen nach speziellen Parametern.

**Comment by xdoo** [comment]
> Ich sehe es anders: Der Nutzer möchte mit möglichst wenigen Schritten an das gesuchte Objekt kommen. Genau darum geht es in diesem Issue. Ob der Nutzer sucht oder filtert ist ihm dabei egal.

@rowe42 sehe ich nicht so. In dem Link oben gibt eine sehr schöne fachliche Unterscheidung:

> filter: filter by 'fruits' and pick an apple
search: search for an apple (when you don't know whether an apple is a fruit!)

Das ist genau der Punkt. Es ist nicht fachlich und schon gar nicht technisch das selbe. Ein weiter wichtige Punkt ist der Algorithmus. Den hat man natürlich bei einer Suche - bei einem Filter hast du das nicht. Das ist fachlich und technisch völlig unterschiedlich.

**Comment by xdoo** [comment]
@Baumfrosch kann ich machen.

Wir haben die Suche auf Basis von Lucene implementiert. Alle Attribute, die als Mainfeature in der DSL gekennzeichnet werden landen im Suchmaschinen Index. Was das alles kann siehe hier:

https://lucene.apache.org/core/

**Comment by Baumfrosch** [comment]
> Ich möchte mir NICHT eine kryptische Syntax merken müssen (z.B. "nachname contains werner"), die ich dann ein ein einzelnes Suchfeld eintippen muss, sondern ich will hier in der Oberfläche möglichst gut geführt werden

Die Alternative zu einer kryptischen Syntax ist aber ein sehr komplexer Suchdialog. Du willst ja nicht nur nach einem Attribut suchen, sondern nach mehreren. Du willst UND- und ODER-Verknüpfungen. Du willst Vergleichsoperatoren. Ehe für alle möglichen Fälle durch den Dialog geführt wirst, schreibst du vielleicht doch lieber "Nachname: Müller".

Ich würde aber trotzdem nicht Suchen mit Filtern vermischen. Wenn du über die Tabellen-Header suchst, musst du nach verlassen des Feldes zum Server. Das macht keinen Spaß. Ich glaube Anwender können Suchen und Filtern mittlerweilen unterscheiden.

**Comment by rowe42** [comment]
@Baumfrosch 
Ich habe schon erklärt, wie ich es mir vom Suchdialog her vorstelle, nämlich über Suchfelder direkt über den Spalten. Das ermöglicht dann nur UND-Verknüpfungen über die Spalten, aber ich behaupte, dass das in den meisten Fällen ausreicht. Wenn wir wollen, können wir für "Power-User" immer noch ein generisches Freitext-Suchfeld anbieten, in dem dann auch ODER-Verknüpfungen über eine kryptische Syntax möglich sind.

Ich verstehe nicht ganz, wo das Problem ist, wenn wir (z.B. beim Tab-out aus einem Suchfeld) zum Server gehen und die Liste holen:
- das vaadin-grid holt und zeigt nur die ersten X Elemente der Suche (d.h. es kommen nicht riesige Datenmengen)
- bei einer halbwegs vernünftigen Anbindung fühlt sich das an wie bei einem Autocompleter, der geht auch für jeden neu eingegebenen Buchstaben zum Server und es stört nicht und geht schnell.

**Comment by Baumfrosch** [comment]
Ich versuche mal das Ergebnis aus meinem gestrigen Gespräch mit @xdoo und @rowe42 festzuhalten:

Fall 1. Geringes Mengengerüst
An der Oberfläche gibt es eine Tabelle mit Filtern, es gibt kein Suchfeld. Ich lese alle Objekte vom Server und nutze Filtern um die Menge einzuschränken. Paginierung gibt es nicht.

Fall 2, Großes Mengengerüst
Es gibt EIN Suchfeld und einen Such-Button. Im Suchfeld können mehrere Such-Strings eingegeben werden, die mit UND verknüpft auf alle Mainfeature an.
Komplexere Abfragen können mit Such-Operatoren durchgeführt werden. Ich prüfe, was Lucene hier bietet. Hilfe nehme ich gern entgegen.
Die so eingeschränkte Treffermenge wird in den Client geladen und dort mit den Filtern der Tabelle weiter eingeschränkt.
Paginierung gibt es nicht.

Ein Suchfeld, dass ab dem dritten Zeichen vom Server liest, sollte auf Grund des Traffics eher vermieden werden. Ein Suchfeld mit Button vermittelt auch klar den Unterschied zwischen Suchen und Filtern.

Wir glauben mit diesem einfachen Ansatz alle Anforderungen erschlagen zu können. Kritisch ist die komplexere Such-Syntax. Dialoge, die solch eine komplexe Suche abbilden können, sind in der Regel aber auch nicht einfach zu bedienen.

**Comment by Baumfrosch** [comment]
Nachtrag: wir wollen außerdem die letzten Eingaben ins Suchfeld serverseitig speichern. Das vereinfacht die Eingabe vor allem bei komplexen, immer wiederkehrenden Suchen.

**Comment by xdoo** [comment]
Letzteres nennt sich "Suggester".

**Comment by Baumfrosch** [comment]
Again what learnt

**Comment by rowe42** [comment]
Wenn wir das wirklich so machen (und nicht mit mehreren, typisierten Suchfeldern, wie ich vorgeschlagen habe), sollten wir folgende Anforderungen erfüllen:
- Es sollte klar ersichtlich sein, wie viele Suchergebnisse gefunden wurden (z.B. durch einen Text "Suche ergab 78 Ergebnisse") und ob das Ergebnis vollständig ist oder aufgrund der laxen Suchkriterien nur eine Teilmenge ist ("Suche ergab mehr als 100 Ergebnisse. Achtung: Es werden nur die ersten 100 Ergebnisse angezeigt. Bitte verfeinern Sie ggf. die Suche."). im letzten Fall kann man sich nämlich das Filtern sparen, da der gesuchte Fall ggf. gar nicht in der Liste ist.
- Es sollte an einfach zugänglicher Stelle (z.B. in einem Button direkt neben dem Suchfeld) eine Erklärung der Such-Syntax aufgeführt sein (wenn man z.B. bei den Github Issues auf den Pfeil bei "Filters" klickt, gibt es als letzten Punkt im Menü "View advanced search syntax", was auf diese Hilfe-Seite führt: https://help.github.com/articles/searching-issues-and-pull-requests/)
- Es sollte auch klar ersichtlich sein, in welchen Feldern das Suchfeld sucht. Nach meinem Verständnis sind das die, die in der DSL als "searchable" gekennzeichnet sind. Nachdem das nicht unbedingt identisch ist mit den Feldern, die in der Tabelle angezeigt werden (das sind die, die in der DSL als "mainFeature" gekennzeichnet sind), muss man das irgendwo hinschreiben oder anders kenntlich machen.

Vorstellbar wäre darüber hinaus:
Wie bei den Github Issues wird bereits eine häufig genutzte Suche standardmäßig vorbelegt (hier: "is:issue is:open", bei uns z.B. "status:offen und Bearbeiter:ich")

Noch eine Konkretisierung zu "mit den Filtern der Tabelle weiter eingeschränkt": Wir wollen also einen textuellen Filter über jede Spalte legen, wie im diesem Issue von mir ganz oben als Screenshot dargestellt. @ejcsid dies dann also bitte noch in die Tabelle einbauen. Zusätzlich sollten wir - wenn das möglich ist - trotzdem noch sortieren können.

**Comment by xdoo** [comment]
1. Punkt:
Finde auch, dass man die Anzahl der Treffer sehen sollte. Ich würde aber keine Teilmengen schicken. Wenn das Ergebnis zu groß ist (was zu groß ist, das ist fachlich), dann gibt es eine entsprechende Meldung. 

2. Punkt:
Finde ich eine gute Idee das so wie Github zu machen. Auf schon Standardsuchen anzubieten. Das muss allerdings ein konfigurierbares Feature sein.

3. Punkt:
Ich glaube nicht, dass das wirklich eine Relevanz hat. In der Regel ergibt sich aus der Fachlichkeit, nach was die suchen. Genau diese Attribute müssen als 'searchable' gekennzeichnet sein. Dann machen die Nutzer das schon intuitiv richtig. 

Das Filtern würde ich echt vom Aufwand abhängig machen. Da musst du was dazu sagen, @ejcsid . Wir haben hier so ein mächtiges Suchwerkzeug, dass wir alles was ein Filter kann damit abbilden können (ohne Zusatzaufwand). Für mich macht eine Kombination Suche / Filter keinen Sinn. Ein Filter macht für mich nur dann Sinn, wenn wir keine Suche haben. Ich bin überzeugt, dass in den meisten Fällen die Suche genau das ist, was die Poweruser wollen.

@Baumfrosch, die Syntax zur Suche ist übrigens hier dokumentiert: https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

**Comment by Baumfrosch** [comment]
Gute Punkte, @rowe42 !

zu 1) Warum ist die Anzahl fachlich, @xdoo ? Warum lesen wir nicht einfach, was technisch möglich oder sinnvoll ist?

zu 2) Genial die Lösung in GitHub. Ich habe eine Auswahl und bleibe super flexibel! 
Meinst du mit "konfigurierbar", dass ich die Standard-Filter in einer Konfigurationsdatei ablege, @xdoo ?
Für die Fields muss sichergestellt sein, dass sie zu denen auf der Maske passen, richtig? Anspruchsvolles Suchen können nur interne Mitarbeiter, muss also nicht internationalisiert werden.

zu 3) hier ist sicherlich die Erwartungshaltung, dass nach allen Attributen gesucht werden kann. Muss man das überhaupt einschränken, @xdoo ?

Ich hatte verstanden, dass Filtern in der Tabellenkomponente schon dabei ist. Aber da habe ich wohl meine Frage nicht richtig formuliert.

Die Lucene-Parsersynthax hab ich mir angeschaut. Sehr mächtig. Das muss reichen.

Insbesondere nachdem ich das Filter-Feature von GitHub gesehen habe, bin ich absolut überzeugt, dass wir hier den richtigen Weg gehen.

**Comment by xdoo** [comment]
1. Technisch möglich ist das was der Rechner aushält. Der sagt es dem Nutzer dann schon, wenn er nicht mehr kann :) Es gibt in der Regel eine fachliche Obergrenze für eine sinnvolle Ergebnismenge. In EWO sind das z.B. 1000 Ergebnissätze bei einer Personensuche. Hat das Ergebnis mehr, dann wird dem Nutzer gesagt, dass er doch bitte seine Suche verfeinern soll. In einem anderen Kontext kann diese  Grenze wesentlich niedriger liegen.
2. Woher die kommen ist erst einmal egal. Wichtig ist, dass ich sie von außen in die Komponente bringe ohne diese zu verändern. Die können auch in der DB gespeichert sein.
3. Wenn das die Erwartungshaltung ist, dann wird es so in der DSL modelliert. Ist das nicht die Erwartungshaltung, dann wird es eben anders modelliert. Wieder das Beispiel Personensuche. Hier ist die Erwartungshaltung, dass ich nach Vorname, Nachname, Geburtsdatum suchen kann (obwohl eine Person deutlich mehr Attribute hat). Jeder der das Verfahren nutzt, weiß das und macht das so. Viele Dinge machen fachlich ja auch gar keinen Sinn. Wie groß ist beispielsweise die Ergebnismenge bei der Suche nach "Hans Meier 1975 weiblich"? Vermutlich null. Und wenn ich nach "Hans Meier 1975 männlich" suche, dann ist sie exakt so groß wie bei der Suche nach "Hans Meier 1975". Das ist eine fachliche Entscheidung, die auch technisch Sinn macht. Mehr Attribute in der Suche bedeuten einen größeren Index und mehr Aufwand beim indexieren. 

Wenn ich mir so den Code der Tabellen so ansehe, dann habe ich nicht das Gefühl, dass es Filter kostenlos gibt. Noch dazu müssen ja generisch oder genrierbar sein. Aber dazu sollte @ejcsid etwas sagen.

**Comment by rowe42** [comment]
Zu 1.: Wir sollten einen Standard-Wert generieren, z.B. 100. Der Entwickler muss das aber leicht anpassen können.
Zu 3.: Ich bin trotzdem der Meinung, dass man es irgendwie kenntlich machen sollte, welche Felder in die Suche einbezogen werden. Aber da beuge ich mich gern der Mehrheit, wenn ihr das sonst alle für nicht notwendig haltet.

Ich habe mir auch kurz den Filtercode angeschaut. Denke schon, dass das relativ einfach geht. Habe es mal kurz ausprobiert:
Folgender Code:
```
            <vaadin-grid-column>
                <template class="header">
                    <vaadin-grid-sorter path="street">Straße</vaadin-grid-sorter>
                    <vaadin-grid-filter aria-label="Straße" path="street" value="[[_filterStreetItem]]">
                    </vaadin-grid-filter>
                </template>
                <template>[[item.street]]</template>
            </vaadin-grid-column>
```
führt zu folgendem Ergebnis:
![bildschirmfoto vom 2018-01-17 12-40-26](https://user-images.githubusercontent.com/25983841/35041069-cae32c6c-fb83-11e7-8eb0-a4d10ddb0233.png)

Man kann in das Textfeld etwas tippen, dann wird gefiltert:
![bildschirmfoto vom 2018-01-17 12-42-23](https://user-images.githubusercontent.com/25983841/35041108-e4d061a8-fb83-11e7-9459-1bbec141dbbd.png)

**Comment by Baumfrosch** [comment]
Zu 1) Standard-Wert klingt vernünftig, dann aber mehr als 100, sonst stoße ich da gleich an. 1000 fände ich besser.

Zu 3) Reicht es nicht, wenn wir das ins Anwenderhandbuch oder in die Online-Hilfe schreiben?

Das Filtern sieht ja einfach aus, soll aber @ejcsid entscheiden. Z.B. ist ja noch Sortieren zu bedenken.

**Comment by rowe42** [comment]
In meinem Versuch oben ist sowohl Filtern als auch Sortieren (beim Klick auf das Label, z.B. "Straße") enthalten und funktionsfähig.

**Comment by ejcsid** [comment]
Ich habe folgendes verstanden:

1. Das Feld oberhalb der Liste dient zur Suche im Backend, nicht zum Filtern. Die Suche soll wie in Github realisiert werden und wird bereits vom Backend unterstützt. Allerdings sollen die Datensätze erst angezeigt werden, wenn gesucht wurde. Das Suchen würde ich durch Eingabe von "Enter" auslösen, wenn gewünscht, zusätzlich auch durch einen Button.
2. Es soll angezeigt werden, wie viele Datensätze gefunden wurden. Wenn die Suche zu viele Datensätze liefert, soll ein Hinweis kommen, dass die Suche verfeinert wird. Dies muss vom Backend unterstützt werden. Ist das bereits der Fall? Sonst sollten wir dazu ein extra Ticket aufmachen.
3. Es gibt den Wunsch, Filter pro Feld zu setzen, siehe Lösungsvorschlag von @rowe42.
Habe ich was vergessen?

Ich komme jetzt leider etwas spät, aber habe an der offline-Diskussion ja nicht teilnehmen können. Mir sind folgende Gedanken gekommen:
1. Wenn ich ein Such-Feld habe, über das ich nach Werten in genau einem Feld suchen kann (z.B. Nachname:Werner), warum brauche ich dann in der Liste genau den gleichen Filter nochmal?
2. Ich finde das Filtern-Feld über der Spalte optisch nicht ansprechend.
3. Es gibt ja Tabellen, bei denen erwartungsgemäß wenig Datensätze drin sein werden (sagen wir mal <100) und welche, bei denen es viele Datensätze gibt. Müssen die gleich aufgebaut sein? Bei den kleinen Tabellen könnte so ein Filtern-Feld (à la google) praktisch sein.

**Comment by ejcsid** [comment]
Zu der Liste was zu tun ist, kommt noch dieser Punkt:
4. Das Frontend muss die Eingabe im Suchfeld, in eine für lucene verständliche Anweisung übersetzung. Wir können den NutzerInnen ja nicht zumuten, dass sie z.B. firstName:Werner im Suche-Feld eingeben.

**Comment by xdoo** [comment]
> Wenn ich ein Such-Feld habe, über das ich nach Werten in genau einem Feld suchen kann (z.B. Nachname:Werner), warum brauche ich dann in der Liste genau den gleichen Filter nochmal?

Das frage ich mich auch :) Ich würde sagen man braucht nur das Suchfeld.

>Ich finde das Filtern-Feld über der Spalte optisch nicht ansprechend.

Dito.

>Es gibt ja Tabellen, bei denen erwartungsgemäß wenig Datensätze drin sein werden (sagen wir mal <100) und welche, bei denen es viele Datensätze gibt. Müssen die gleich aufgebaut sein? Bei den kleinen Tabellen könnte so ein Filtern-Feld (à la google) praktisch sein.

Aber selbst die würde man im ersten Schritt über eine Suche klein bekommen.

> 4. Das Frontend muss die Eingabe im Suchfeld, in eine für lucene verständliche Anweisung übersetzung. Wir können den NutzerInnen ja nicht zumuten, dass sie z.B. firstName:Werner im Suche-Feld eingeben.

Ich würde es mit der Zumutung zumindest mal probieren. Mit den vorgefertigten Queries a la github ist das eh leicht. Und viele von denen sitzen heute vor schwarzen Bildschirmen und tragen fachliche Codes in Felder ein. Die können einiges ertragen ;)

**Comment by ejcsid** [comment]
Kleine Tabellen könnte man aber gleich anzeigen und nicht erst wenn der Nutzer was eingegeben hat. Dann würde man also eher Filtern statt Suchen

**Comment by xdoo** [comment]
Das stimmt. Ich würde sagen wir sollten entweder suchen, dann ist die Tabelle initial leer. Oder wir machen ein prefetch und dann ist die Tabelle voll. Dann macht filtern Sinn. Im zweiten Fall muss man aber bedenken, dass sich die Datenbasis jederzeit ändern kann.

**Comment by ejcsid** [comment]
Zur Suche: Für die Nutzer wäre es aber schon einfacher, wenn sie bei der Suche den Titel in der Tabelle zum entsprechenden Feld verwenden können (das ist bei github ja auch so). Ich schau mal, ob sich das "Übersetzen" leicht realisieren lässt.

**Comment by Baumfrosch** [comment]
> Für die Nutzer wäre es aber schon einfacher, wenn sie bei der Suche den Titel in der Tabelle zum entsprechenden Feld verwenden können (das ist bei github ja auch so). Ich schau mal, ob sich das "Übersetzen" leicht realisieren lässt.
Ja, das denke ich auch, @ejcsid . Die Anwender und viele Kollegen werden sehr skeptisch gegenüber dem Suchfeld sein. Durch den Suggester und die vorgefertigten Queries wird es deutlich besser. Trotzdem müssen die Bezeichner in der Tabelle und im Suchfeld die gleichen sein. Bekommt man das nicht auch über die Internationalisierung hin, @xdoo ?
Eine Frage, die ich mir stelle: Wie bekommen wir die Individualisierung hin? Bei GitHub "Your Issues". Bei uns z.B. "Meine Fälle" oder "Fälle meiner Abteilung"

**Comment by Baumfrosch** [comment]
> Das stimmt. Ich würde sagen wir sollten entweder suchen, dann ist die Tabelle initial leer. Oder wir machen ein prefetch und dann ist die Tabelle voll. Dann macht filtern Sinn. Im zweiten Fall muss man aber bedenken, dass sich die Datenbasis jederzeit ändern kann.

Ich denke jetzt ist klar, dass wir bei großen Datenmengen suchen. Wir wissen wie das Suchfeld funktioniert.

Aber wie funktioniert das Filtern bei kleinen Datenmengen, @xdoo , @ejcsid ?
Es gibt ein Feld, aber ohne Such-Button. Wenn ich etwas eingebe wir on-the-fly gefiltert ab dem ersten eingegeben Zeichen. Die gleiche Syntax wie beim Suchen ist aber nicht erlaubt, weil wir nicht suchen. Aber so etwas wie "Vorname:Roland Nachname:Werner" wäre aber vielleicht doch sinnvoll bzw. wird vom Anwender erwartet. Vorgefertigte Filter braucht man nicht bei kleinen Datenmengen.
Eine Grenze darf es nicht geben. Wenn sich das Projekt einmal auf Grund der geringen Datenmenge für eine Filtertabelle entschieden habe, wird immer alles gelesen, auch wenn das Volumen größer wird.

Paginierung brauchen wir in keinem der Fälle.

**Comment by Baumfrosch** [comment]
Und noch eine Idee zum Filtern. Bei unserem alten Kalender konnte ich z.B. "Wag Mat" eingeben und bekam "Matthias Wagner". Bei meinen Google-Kontakten geht das nicht. Geht das bei unserem Filter?

**Comment by Baumfrosch** [comment]
> Wenn ich ein Such-Feld habe, über das ich nach Werten in genau einem Feld suchen kann (z.B. Nachname:Werner), warum brauche ich dann in der Liste genau den gleichen Filter nochmal?

Im Sinne von KISS lassen wir die Filterfelder über den Tabellen erstmal weg und schauen wie es bei Test-Usern ankommt., @rowe42 @xdoo @ejcsid

**Comment by xdoo** [comment]
Wag Mat würde m. M. nach sowohl bei Suchen (wenn man die Attribute als searchable definiert) als auch Filtern gehen. Ich vermute bei Google geht das nicht, weil die eine Volltextsuche über alle Wörter machen und dann hat weder Wag genügen Ähnlichkeit mit Wagner, noch Mat mit Mathias.

**Comment by ejcsid** [comment]
Neues Ticket #102 erstellt. Hier nur noch das Thema Suche (über Backend) besprechen.

**Comment by ejcsid** [comment]
Ich fasse nochmal zusammen:

1. Suche soll wie bei github möglich sein: "suchfeld":"suchstring"
2. "suchfeld" soll lauten wie die Überschrift der Tabellenspalte. Das Feld muss dann in ein für lucene verständliches Wort übersetzt werden. Internationalisierung geht nicht so einfach, weil das zurückübersetzt wird.
3. Der Inhalt der Tabelle wird erst nach Eingabe eines suchstrings angezeigt.
4. Es kann voreingestellte Suchstrings geben (z.B. offen:true, bearbeiter:aktuellerbenutzer)
5. Bei Github können die angezeigten Datensätze nach bestimmten Kriterien filtern (z.B. Meilenstein, Label etc.). Das entspricht dem aufklappbaren Filter in der Keepers-Liste. Da dieser fachspezifisch ist, muss dieser manuell implementiert werden. Der aufklappbare Filter ist optional.

Ist das so ok?

**Comment by ejcsid** [comment]
Anforderung 6b (Wenn die Suche zu viele Datensätze liefert, soll ein Hinweis kommen...) in Ticket #108 verschoben, da vorher das Backend (siehe Ticket #107) angepasst werden muss.
