### ISSUE TITLE
Liste-Pagination: Beim Sortieren werden nur die Zeilen der jeweiligen Seite sortiert

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#61]
Pagination als Option eingeführt, aber in diesem Fall werden nur die Datensätze der jeweiligen Seite sortiert (siehe: vaadin-grid issues: 1051). Vaadin hat diesen issue akzeptiert und wird ihn umsetzen.

**Comment by xdoo** [comment]
Hat @Baumfrosch weg diskutiert.
