### ISSUE TITLE
Liste Pagination: Bei Änderung der Seiten-Anzahl kann leere Seite angezeigt werden

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#63]
Navigiere zu einer Seite > 1, filtere die Datensätze, so dass weniger Seite angezeigt werden als die aktuelle Seite. Folge: Es wird eine leere Seite angezeigt.

Vorschlag, die Liste soll in diesem Fall auf die erste Seite springen.

**Comment by xdoo** [comment]
@Baumfrosch hat das weg diskutiert :)
