### ISSUE TITLE
Uploads

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#64]
Wie wollen wir mit Uploads umgehen?
Soll man ein Upload-Feld modellieren und generieren können oder muss man das von Hand ergänzen?

@xdoo @dragonfly28 @ejcsid

**Comment by xdoo** [comment]
Ja, aber das ist m. M. nach nicht so leicht wie es sich anhört. Dafür fehlt uns nach meinem Wissensstand auch alles im Backend und der entsprechende Datentyp in der DSL. Weißt du da mehr @FabianWilms ?

**Comment by FabianWilms** [comment]
Es gibt derzeit keine offizielle Möglichkeit Daten hochzuladen. Es steht natürlich jedem Entwickler offen ein Feld mit Datentyp String dazu zu missbrauchen dort data-uris zu speichern.

Haben wir in der DSL auch nicht umsetzen wollen, weil es so viele Möglichkeiten gibt die sich je nach Dateityp und Verwendungsart unterscheiden. Speicher ich die Daten als Blob mit in der Datenbank? Oder in Form eines Strings als data-uri? Lade ich die Dateien auf einem eigenen Filter hoch und speichere nur den Pfad zur Datei?

Würde ich daher auch nicht als Feature für barrakuda betrachten. Auch deshalb, weil eine eigene Implementierung, wenn dies gefordert wird, keine größer zeitlicher Aufwand ist.

**Comment by Baumfrosch** [comment]
Insbesondere wenn es zig Möglichkeiten gibt, fände ich es gut, wenn wir hierzu Vorgaben machen. Das muss nicht bedeuten, dass es nur eine Lösung gibt und auch nicht, dass etwas in Barrakuda dazu implementiert wird.
Es wäre also möglich, dass wir mit Bezweck eine Lösung implementieren, die dann als Best-Practice deklariert wird.
Schön fänd ich einen Upload des Dokuments und Speichern samt Metadaten ins DMS. Im Microservice wäre dann nur noch der Link.

**Comment by xdoo** [comment]
Ich würde dann aber vorschlagen, von diesem "Meta Issue" weg zu gehen und für die Wege, die implementiert werden sollen ein eigenes Issue zu eröffnen. Das kann man dann entsprechend priorisieren und spezifisch diskutieren. 

Dieses Issue sollte danach geschlossen werden.

**Comment by rowe42** [comment]
@xdoo Ich kann mir jetzt nicht ganz vorstellen, wie du das haben willst. Bitte erzeuge das Issue wie du meinst. Ich verlinke dann darauf und schließe dieses "Meta Issue".

**Comment by xdoo** [comment]
Für DMS habe ich das Issue #67 erstellt.

**Comment by xdoo** [comment]
Für DB habe ich das Issue #68 erstellt.

Weitere Optionen würde ich an dieser Stelle nicht anbieten. Wie seht ihr das?

**Comment by xdoo** [comment]
Wurde in einzelne Tickets aufgeteilt.
