### ISSUE TITLE
Tests für Formulare

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#65]
Für die Formulare müssen noch (JavaScript) Tests erstellt werden. In diesem Rahmen ist zu prüfen, inwieweit es sinnvoll ist Tests gleich mit zu generieren.

**Comment by eidottermihi** [comment]
An dieser Stelle würde dann doch die im "BeZweck & Friends"-Meeting angedachte Testsetup (u.a. Selenium Grid) ins Spiel kommen?
Die Polymer CLI setzt zu diesem Zweck auf [web-component-tester](https://github.com/Polymer/web-component-tester) auf. Ausführliche Dokumentation hierzu gibt es direkt von Polymer: https://www.polymer-project.org/2.0/docs/tools/tests
Im Hintergrund kommt dabei u.a. 
* Mocha
* Chai
* Sinon
* Selenium

zum Einsatz.

@xdoo Du hattest im Meeting ``Karma`` genannt. Ist das hierfür überhaupt relevant?

**Comment by xdoo** [comment]
Mit Karma könnte man aus meiner Sicht Selenium und Polymer CLI ersetzen. Siehe:
https://karma-runner.github.io/2.0/index.html

Es ist letztendlich eine Frage welche Umgebung besser zu unseren Bedürfnissen passt. Diese Frage kann ich nicht so ad hock beantworten. Wenn man die Tests in Mocha schreibt verbaut man sich nichts. Da funktioniert sowohl mit dem oben beschriebenen Stack, als auch mit Karma.

**Comment by rowe42** [comment]
@eidottermihi Aus Diskussion mit @Baumfrosch: Ist das ein Generator-Issue oder ein BeZweck-Issue? Bitte in das jeweilige Repo umziehen und hier zu machen.

**Comment by eidottermihi** [comment]
Für abstrakte Components (wie z.B. animad-form-behavior) würden sich generierte Tests aus meiner Sicht schon lohnen, ich habe daher intern ein Issue (Nr. 299) beim Generator erstellt.
Für die tatsächlichen Formulare (z.B. animad-animal-create-form) stelle ich mir generierte Tests schwieriger vor.

Und solange wir in BeZweck ausschließlich die generierten Formulare nutzen, sollten die Unit-Tests dazu aus dem Generat kommen.
