### ISSUE TITLE
Einsatz von Icons

### ISSUE THREAD

**Issue by Baumfrosch** [xdoo/lhm_animad_admin_html5#66]
Ich halte den Einsatz von Icons für sehr sinnvoll. Icons können schnell erfasst werden und ersparen einem die Internationalisierung. Für Sachbearbeiter ist die Internationalisierung nicht so spannend, im Hinblick auf eGov wird das aber zu einer echten Herausforderung. 

Wenn ihr auch der Meinung seid, würde ich das Thema mal angehen und versuchen ein paar Vorgaben zu machen.

Hier eine interessante Antwort auf eine Stadtratsanfrage zu mehrsprachigen Hinweisschildern:
"Der Vorteil von Piktogrammen ist, dass sie unabhängig von Sprache und Herkunft von allen Personen gleichermaßen verstanden werden. In München leben Menschen aus über 180 Nationen, die mehr als 43 verschiedene Sprachen sprechen. Nicht alle von Ihnen können wir mit einem für sie verständlichen Texthinweis erreichen und die Auswahl bestimmter Sprachen würde immer zu einer „Benachteiligung“ der anderen führen. Daher sind fremdsprachige Texthinweise aus Sicht des Bürgerbüros keine
gewinnbringende Alternative oder Ergänzung zu den universell verständlichen Piktogrammen. Dies vor allem auch, weil die Erfahrungen im Parteiverkehr zeigen, dass das Angebot auch von fremdsprachigen Kundinnen und Kunden tatsächlich sehr gut verstanden und angenommen wird.

**Comment by xdoo** [comment]
Für die Implementierung haben wir es in der Vaadin GWT Version so gemacht, dass wir die Icons konfigurierbar gemacht haben. Dafür haben wir die i18n Mechanismen verwendet (ja, ich bin mir bewusst, dass dies an genau dieser Stelle nicht die korrekte akademische Lösung ist, aber es ist eine pragmatische...). Dadurch hat man die Frage der richtigen Icons aus der Modellierung und aus der Programmierung heraus gehalten. 

Das sollte uns nicht davon abhalten, hier Vorgaben / best practices zu definieren - sie würden nur die Implementierung nicht beeinflussen.

**Comment by xdoo** [comment]
@Baumfrosch, ich habe dir mal einen Screenshot zum Drucken von https://materialdesignicons.com/ gemacht :)

![screenshot-2018-1-16 material design icons](https://user-images.githubusercontent.com/712911/34975006-06964e46-fa90-11e7-9a76-685cfaf2f5b2.png)

**Comment by Baumfrosch** [comment]
Wo dokumentiere ich meine Überlegungen am Besten, @xdoo ?
Im internen Wiki?

**Comment by xdoo** [comment]
Ja, das passt dort besser als hier.

**Comment by ejcsid** [comment]
@xdoo Bitte olym** zuweisen.

**Comment by rowe42** [comment]
@olympialice das hier sollte dir zugewiesen werden, aber kann nur @xdoo 
Kannst du das bitte in deinem Wiki-Artikel überarbeiten (angleichen an das, was wir aktuell generieren bzw. mit mir diskutieren) und dann den Issue schließen.

**Comment by olympialice** [comment]
Icons sind im internen Wiki mit Aktion, Einsatzbeispiel und Quelle beschrieben
