### ISSUE TITLE
Technisches Datenmodell BeZweck modellieren

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#69]
Nach Abstimmung mit @Baumfrosch soll das bestehende BeZweck Datenmodell vom TRE unter Unterstützung durch mich und Helmut im Rahmen des technischen Datenmodells so ummodelliert werden, dass die generischen Entities wie "Fall" und "Aktivität" in verschiedene Entitäten aufgebrochen werden, um abhängige Elemente (wenn Fall-Type X dann wird Feld Y benötigt) zu vermeiden.

@Baumfrosch hat sich bereiterklärt, den dann vorliegenden Entwurf mit seiner Expertise zu betrachten und ggf. noch zu überarbeiten.

Dieses Issue dient als Merker für dieses Arbeitspaket.

**Comment by xdoo** [comment]
Ich würde vorschlagen alle "BeZweck" Dinge auch als Issue im BeZweck Repo zu diskutieren. Das hat m.M.  nach nichts mit der Referenzimplementierung zu tun.

**Comment by Baumfrosch** [comment]
Ich finde auch, dass wir das trennen sollten. Ich möchte auch nicht, dass wir Bezweck-Sachverhalte öffentlich diskutieren. D.h. die konkreten Bezweck-Punkte im BeZweck-Repo, die sich aus der Diskussion ergebenden Issues, die für die Architektur und den Generator von generellem Interesse sind bzw. die Diskussion, ob sie von generellem Interesse sind, hier.

**Comment by rowe42** [comment]
Das wird unweigerlich zu Dopplungen / Überlappungen führen. Z.B. müssen wir das Thema Service-Schnitt dann sowohl dort als auch hier führen und die Issues miteinander verlinken.
Mir ist kein BeZweck-Repo bekannt. Ich werde Helmut darauf ansprechen - entweder sein TRE erzeugt eines oder ich mache das und muss dann später die Ownership übertragen. Ich nehme an, es sollte dann im Gitlab angelegt werden.

**Comment by rowe42** [comment]
Machen wir außerhalb des issue. Wird geschlossen.
