### ISSUE TITLE
<paper-input> mit type Date inkonsistentes Verhalten

### ISSUE THREAD

**Issue by FabianWilms** [xdoo/lhm_animad_admin_html5#7]
In älteren Browsern (Firefox 45.9) wird hier nur ein Textfeld angezeigt. In Chrome (v51) geht hier die ANzeige mit dem im Label angezeigten Format auseinander.

aus

```
<paper-input
    type="date" 
    name="employmentdate" 
    required 
    label="Einstellungsdatum (yyyy-mm-dd)" 
    value="{{data.employmentdate}}" 
    auto-validate 
    required 
    pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}">
</paper-input>
```

wird in Chrome

![chrome](https://user-images.githubusercontent.com/10800158/32946241-05374a5a-cb97-11e7-9f44-90587159d8f5.png)

**Comment by xdoo** [comment]
Für Firefox (ich weiß jetzt nicht an welcher Version) gibt es einen Workaround:

about:config

dom.forms.datetime -> set to true

Aber insgesamt ist das Element nicht ideal. Kennst du eine Alternative?

**Comment by xdoo** [comment]
Die Felder sind halt lokalisiert. Wenn du auf Englisch umstellst dann passt es vermutlich wieder. Was ich total geil finde sind die lokalisierten Hinweise über falsch ausgefüllten Felder. Z.B. wenn du eine minimale Anzahl an Buchstaben definierst.

**Comment by peter-mueller** [comment]
Finde das neue date input super, weil es jetzt auch im neuen Firefox drin ist.

https://caniuse.com/#search=date

**Comment by xdoo** [comment]
@peter-mueller stimmt. Auf dem DSL Rechner geht es schon. Also auf dem internen Image so um 2020 rum ;)

**Comment by xdoo** [comment]
Was machen wir damit? @FabianWilms @peter-mueller

**Comment by FabianWilms** [comment]
Das kommt darauf an, was ihr euch für die Referenz-Architektur als Anforderungen gesetzt habt. Welche Browser sollen in welchen Versionen mindestens unterstütz werden? Wenn ihr nur alle aktuellen Supporten wollt würde ich es so lassen.

Als alternative lässt sich der https://www.webcomponents.org/element/vaadin/vaadin-date-picker/v3.0.0-alpha5 ganz gut verwenden. Bringt aber natürlich wesentlich mehr overhead mit sich als die momentane Lösung.

**Comment by xdoo** [comment]
Dann lassen wir das Ticket mal offen.

Das Vaadin Ding ist ja wieder mal hässlich. Was ich ganz gut gelungen finde ist der hier: https://vuematerial.io/components/datepicker Ist halt keine Webkomponente :)

**Comment by FabianWilms** [comment]
Was ist mit dem hier:

https://www.webcomponents.org/element/fooloomanzoo/datetime-picker/demo/demo/date-picker.html

**Comment by xdoo** [comment]
So schön wie der von vue Material ist er nicht ;)

Wir behalten den einfach mal als Fallback im Hinterkopf und sollten wir mit dem Default Probleme bekommen, dann nehmen wir den. Solange bleibt das Ticket offen.

**Comment by rowe42** [comment]
Ich habe hierzu ein Custom-Tag programmiert (common-libs/animad-date-input), das prüft, ob der Browser den input-Type date unterstützt und sonst den vaadin-date-picker verwendet.
Der ist nicht besonders schön, aber es funktioniert.

@FabianWilms @xdoo schaut euch das mal kurz an, ob das für euch so passt. Dann würde ich das Issue schließen wollen.

Wenn wir in ein paar Monaten weiter sind (i.e. Firefox 58) kann man das ja wieder zurückbauen...

**Comment by FabianWilms** [comment]
Sollte so passen. Ich würde aber bei der Prüf-Funktion das erstellte input-Elememt noch wieder aus dem DOM entfernen :stuck_out_tongue:

Laut https://stackoverflow.com/a/10199306 könnte man die Prüfung noch verbessern. Ihr müsst aber entscheiden, ob das Sinnvoll ist.

**Comment by rowe42** [comment]
Habe jetzt noch ein `input.remove();` ergänzt.
Den anderen Vorschlag würde ich nicht machen - klingt mir zu sehr als Hack und außerdem ist das ja nicht für die Ewigkeit - sobald die Browser Inputs vom Typ date nativ unterstützen, sollten wir das "Polyfill" eh wieder raus nehmen.

Eingecheckt in Branch _#244.

**Comment by rowe42** [comment]
Jetzt in master. Schließe das Issue.
