### ISSUE TITLE
Diskussion Service-Schnitt am Beispiel von BeZweck

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#70]
Wir müssen noch definieren, nach welchen Gesichtspunkten eine Anwendung in einzelne Microservices geschnitten werden soll.
Dies muss man einerseits generisch machen (Diskussion der Empfehlungen aus der Community, z.B. striktes DDD nach Eric Evans), andererseits kann es auch helfen, es frühzeitig am Beispiel BeZweck auszuprobieren - dazu sollte aber das technische Datenmodell vorliegen (vgl. #69).

Dieses Issue dient als Merker für dieses Arbeitspaket.

**Comment by xdoo** [comment]
Ich würde vorschlagen alle "BeZweck" Dinge auch als Issue im BeZweck Repo zu diskutieren. Das hat m.M.  nach nichts mit der Referenzimplementierung zu tun.

**Comment by rowe42** [comment]
@Baumfrosch wollte, dass alle ToDos im Rahmen der Referenzarchitektur bis Freitag als Issues dokumentiert sind. Meines Wissens gibt es kein "BeZweck" Repo.
@Baumfrosch Willst du BeZweck-relevante Issues anderswo dokumentiert haben? Und wenn ja, wo?

**Comment by xdoo** [comment]
Ich kann ein privates Repo dafür spendieren, oder wir gehen auf Gitlab (intern). Aus meiner Sicht sollte der travis Build bei generiertem Code nicht so relevant sein.

**Comment by ejcsid** [comment]
@Baumfrosch Wo sollen Tickets für BeZweck bearbeitet werden?

**Comment by Baumfrosch** [comment]
Helmut wollte sich schon seit längerem um ein GitLab Repo kümmern

**Comment by rowe42** [comment]
Machen wir außerhalb des issue. Wird geschlossen.
