### ISSUE TITLE
Security-Tags in den Showcase einbauen

### ISSUE THREAD

**Issue by rowe42** [xdoo/lhm_animad_admin_html5#76]
Bisher existieren die Security-Tags nur als Showcase auf einer eigenen Seite. Wenn wir nun den in Issues #71 definierten Showcase implementieren, sollte das auch die Security-Tags beinhalten.

Ich würde die Permissions dann als Mock bei Mockable.io hinterlegen, damit wir dafür erstmal noch kein Backend brauchen.

**Comment by dragonfly28** [comment]
Vorschlag für den Showcase:
- wir implementieren zwei Rollen "ZOO_KEEPER" und "ZOO_DIRECTOR"
- der ZOO_KEEPER darf bei Tieren und Gehegen alles (READ/WRITE), die anderen Keeper aber nur ansehen (READ).
- der ZOO_KEEPER darf alles, also auch neue Keeper anlegen (READ/WRITE).

**Comment by rowe42** [comment]
Können wir gerne so machen, dass es diese beiden Rollen gibt.
Bitte folgendes bedenken: Bei unserem Ansatz werden die Rollen NICHT im Code hartverdrahtet, sondern im KeyCloak konfiguriert. Der UserService fragt für den aktuellen User beim KeyCloak nach und bekommt direkt die Rechte ("Permissions"), die zu den Rollen des Users gehören. Die Rechte (z.B. "administration_READ_Animal") sind dann im Code an die jeweiligen Komponenten etc. gebunden.

Für den Showcase kann ich wie gesagt bei Mockable erstmal ein bestimmtes Set an Rechten (z.B. eben gerade die für Rolle ZOO_KEEPER) hinterlegen. Oder beide Sets an unterschiedlichen URLs, so dass man beides ausprobierenkann (dann muss ich irgendwo einen Dummy-Umschalter einbauen).

**Comment by rowe42** [comment]
Ist jetzt eingebaut, und zwar genau mit den Rechten wie es das Backend kennt.
Rollen kann man sich selbst im KeyCloak anlegen, wie man möchte.

Was wir noch überlegen sollten ist, ob man bei readonly-permissions auch eine Readonly-Detailmaske bekommt oder nur Lesezugriff auf die Tabelle.
