### ISSUE TITLE
HATEOAS Link für die Suche nach Relationen

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#83]
Wenn wir für ein Objekt Relationen haben, dann benötigen wir in der Payload (HAL) einen Link, über den neue Relationen hinzugefügt werden können. Bei Enclosures schaut das aktuell so aus:

```json
{
  "name": "Elephant's Paradise",
  "cleaningTime": "15:15:15",
  "_links": {
    "self": {
      "href": "http://localhost:39146/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5"
    },
    "enclosure_": {
      "href": "http://localhost:39146/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5"
    },
    "animalList": {
      "href": "http://localhost:39146/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5/animalList"
    }
  }
}
```
Es müsste aber so aussehen:
```json
{
  "name": "Elephant's Paradise",
  "cleaningTime": "15:15:15",
  "_links": {
    "self": {
      "href": "http://localhost:39146/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5"
    },
    "enclosure_": {
      "href": "http://localhost:39146/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5"
    },
    "animalList": {
      "href": "http://localhost:39146/enclosures/3bca5b38-13be-4fd3-b656-fa79a639ddd5/animalList"
    },
    "animals": {
      "href": "http://localhost:39146/animals"
    }
  }
}
```

**Comment by rowe42** [comment]
Habe mir das angesehen. Zunächst einmal musste ich die Spring-Version leicht heben, um einen Bug zu beheben (da sonst der zusätzliche Link zwar in einer einzelnen Entity, aber nicht in der Liste der Entities eingefügt wurde).

Ich habe mal zwei Varianten eingecheckt:
1. (Branch _#83): Code ist in Enclosure_ResourceProcessor.java, das ist eine generierte Do-not-touch-Klasse.
2. (Branch _#83_Alternative): Code ist in Enclosure_ResourceServiceImpl.java, das ist eine Custom-Hook-Klasse, in die der Entwickler Code ergänzen kann.

Nach meinem Verständnis sollten wir in dem Fall 1) wählen, um die Custom-Hook-Klasse nicht schon mit Code zu befüllen (den der Entwickler dann ggf. aus Versehen löscht o.ä.).

@xdoo Bitte bestätige mir kurz, dass du das auch so siehst.

Dann ziehe ich das im entsprechenden Branch noch für Animal und Keeper nach und erstelle einen Merge Request (den ich dir dann auch zuweisen würde, wenn du es dir jetzt eh schon anschaust).

**Comment by xdoo** [comment]
@rowe42 ja, sehe ich genauso. Das ist Code, der GENERELL und IMMER einer bestimmten Logik folgt. Damit gehört er definitiv in 1. In 2. gehört nur Code, der für einen bestimmten Fall verwendet wird.

**Comment by rowe42** [comment]
ok, dann bitte mergen und dann Issue schließen.
