### ISSUE TITLE
Connect the UI with the lhm_animad_admin_service

### ISSUE THREAD

**Issue by dragonfly28** [xdoo/lhm_animad_admin_html5#9]
The lhm_animad_admin_service is ready to use now - next step is to connect the Ui with the REST API of the service;
- is the iron-ajax component sufficient?
- is it worth to investigate in the fetch API?
see -> https://fetch.spec.whatwg.org/
see -> https://developers.google.com/web/updates/2015/03/introduction-to-fetch

**Comment by xdoo** [comment]
Hängt mit #36 zusammen.

**Comment by xdoo** [comment]
@dragonfly28 bitte die entsprechenden Issues referenzieren.

**Comment by rowe42** [comment]
Wird in anderen Issues realisiert. Backend bisher als Mocks angebunden.
