### ISSUE TITLE
falsche Anzeige beim Löschen von Relationen 

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#92]
Löscht man Relationen bei Formularen, so kann es zu Anzeigefehlern kommen. Wenn man drei Relationen hat...
![screenshot-2018-1-18 animad](https://user-images.githubusercontent.com/712911/35102442-475b085c-fc63-11e7-8549-513c280b8e30.png)

...und löscht 'Bernd Brot', so verschwindet 'Max Muster'.

![screenshot-2018-1-18 animad 1](https://user-images.githubusercontent.com/712911/35102502-6c5543a2-fc63-11e7-922d-877e0955777e.png)

Die Daten werden allerdings nur falsch angezeigt. Das liegt an der Kombination `dom-repeat` in Verbindung mit i18n. Die Datenmanipulation dahinter funktioniert wie erwartet.

**Comment by rowe42** [comment]
Habe ich gefixt. Ist schon in master.
@xdoo Kleiner Schönheitsfehler: Man kann offenbar auf so ein List-Element klicken und das wird dann fett gedruckt (sieht man auch in deinem 2. Screenshot oben). Das hat aber keinerlei Funktion und verhält sich komisch (bspw. wird eines automatisch markiert wenn man löscht, obwohl ich es überhaupt nicht angeklickt habe - die Logik dahinter habe ich noch nicht durchschaut).
Da das aber keinerlei negativen Effekt hat (und auch nicht zu diesem Issue gehört) lasse ich das einfach mal und schließe stattdessen dieses Issue.
