### ISSUE TITLE
Auswahllisten sind nicht i18n fähig

### ISSUE THREAD

**Issue by xdoo** [xdoo/lhm_animad_admin_html5#97]
Auswahllisten können aktuell nicht internationalisiert werden. Das Backend erwartet genau die Werte, die in der Auswahlliste stehen. Eine Lösung könnte sein, hier key/value pairs zu verwenden.

**Comment by rowe42** [comment]
Habe das gefixt und unter Branch _#175 eingecheckt.
Ich verwende jetzt noch immer die Werte aus dem Backend, aber als Keys, die ich im Frontend per i18n übersetze.

Ein Beispiel ist das Feld skill von Keeper, zu sehen unter animad-keeper-form.

**Comment by rowe42** [comment]
Ist nun im master.
Dies Werte im locales.json sehen so aus:
```
...
        "skill.cleaning": "Putzen",
        "skill.feeding": "Füttern",
        "skill.breeding": "Züchten",
        "skill.paperwork": "Büroarbeit",
        "skill.taxes": "Steuern",
...
```

Das ist zwar etwas unkonventionell, aber ich wollte dafür nicht noch eine weitere Hierarchie in das locales.json einführen.

Schließe das Issue.
