### ISSUE TITLE
Umsetzung der Suche im Backend wie für Github-Issues

### ISSUE THREAD

**Issue by ejcsid** [xdoo/lhm_animad_admin_html5#99]
Umsetzung der Suche wie bei https://lucene.apache.org/core/2_9_4/queryparsersyntax.html beschrieben. Derzeit liefert die Suche z.B. bei "firstname":"hans" auch einen Datensatz mit firstname=Klara.

**Comment by Baumfrosch** [comment]
Das sehe ich kritisch mit RefArch_2.0

**Comment by xdoo** [comment]
Warum? Derzeit ist das oben genannte Feature nicht implementiert. Aber er würde bei der Suche nach Hans auch einen Datensatz finden, der Hans enthält.

**Comment by Baumfrosch** [comment]
Vielleicht verstehe ich es nur falsch, aber wir hatten eine lange Diskussion zu Issue #60 und waren am Ende der Meinung, dass wir Folgendes implementieren:

1. Suche wie bei https://lucene.apache.org/core/2_9_4/queryparsersyntax.html beschrieben
2. Auswählbare Standard-Filter a la GitHub-Issue-Suche
3. Search Suggestions, die die letzten Such-Ausdrücke anzeigt

Das brauche ich, damit wir komplexe Such-Formulare überflüssig machen können. Ich rechne hier mit vielen Diskussionen. Deshalb brauchen wir das in RefArch_1.0 für BeZweck.

**Comment by xdoo** [comment]
Das ist ein Argument, das für RefArch_1.0 spricht :) Ich ändere es auf RefArch_1.0.

**Comment by ejcsid** [comment]
Ich muss da auch das Frontend anpassen, weil dieses ja dann die neue Suche aufrufen soll. Erstelle ein neues Ticket dafür.

**Comment by ejcsid** [comment]
Backend wurde gemerged.
